import { createInitialState, resetFrames, setFrame, readyFrames } from './state.js';
import { addFileToSlot, decodeFile, loadSampleManifest, resolveSampleUrl, FOCUS_LABELS } from './capture.js';
import { DefocusWorkerClient } from './worker-client.js';
import { messageFor } from './errors.js';

const state = createInitialState(); const client = new DefocusWorkerClient(); const resultUrls = new Set();
const $ = selector => document.querySelector(selector); const slots = $('#capture-slots');
const labels = FOCUS_LABELS;

function renderSlots() { slots.innerHTML = state.frames.map((frame, index) => `<label class="capture-slot" data-slot="${index}"><input class="camera-input" type="file" accept="image/*" capture="environment" data-index="${index}"><span class="exposure-mark">${labels[index]}</span><span class="slot-action">${frame.file ? '已选择' : '拍摄 / 选择'}</span>${frame.url ? `<img src="${frame.url}" alt="${labels[index]}样例">` : ''}</label>`).join(''); slots.querySelectorAll('.camera-input').forEach(input => input.addEventListener('change', async event => { const file = event.target.files?.[0]; if (!file) return; try { await addFileToSlot(state, Number(input.dataset.index), file); renderSlots(); updateReady(); } catch (error) { showError(error); } })); }
function updateReady() { const ready = readyFrames(state); $('#run-button').disabled = !ready; $('#analysis-status').textContent = ready ? '五张照片已准备好，可以开始分析。' : `已准备 ${state.frames.filter(frame => frame.file || frame.bitmap).length}/5 张照片`; }
function showError(error) { const node = $('#error-message'); node.hidden = false; node.textContent = error.code ? `${messageFor(error.code)}${error.detail ? ` ${error.detail}` : ''}` : error.message; }
function clearError() { $('#error-message').hidden = true; $('#error-message').textContent = ''; }
function setProgress(value, stage = '分析中') { $('#progress-panel').hidden = false; $('#progress').value = value; $('#progress-percent').textContent = `${Math.round(value * 100)}%`; $('#progress-stage').textContent = stage; }
function hideResult() { $('#result-panel').hidden = true; $('#result-preview').removeAttribute('src'); $('#confidence-preview').removeAttribute('src'); $('#middle-preview').removeAttribute('src'); resultUrls.forEach(url => URL.revokeObjectURL(url)); resultUrls.clear(); state.result = null; }
function displayResult(result) { state.result = result; $('#result-panel').hidden = false; const depthUrl = URL.createObjectURL(result.depthBitmap); const confidenceUrl = URL.createObjectURL(result.confidenceBitmap); resultUrls.add(depthUrl); resultUrls.add(confidenceUrl); $('#result-preview').src = depthUrl; $('#confidence-preview').src = confidenceUrl; $('#middle-preview').src = state.frames[2].url; $('#result-summary').textContent = `焦点曲线已计算，整体置信度 ${(result.quality * 100).toFixed(0)}%，未完成尺度标定时仅显示相对深度。`; }
async function runEstimate() { clearError(); hideResult(); setProgress(0, '读取五张照片'); const frames = state.frames.map(frame => ({ bitmap: frame.bitmap, width: frame.bitmap.width, height: frame.bitmap.height })); try { const result = await client.run('estimate', { frames, options: { tileSize: 8, minTexture: 0.02, minPeakProminence: 0.08, maxAlignmentErrorPx: 2 } }, value => setProgress(value, '计算焦点评分')); displayResult(result); setProgress(1, '完成'); setTimeout(() => { $('#progress-panel').hidden = true; }, 500); } catch (error) { $('#progress-panel').hidden = true; showError(error); } }
async function useSample() { clearError(); $('#sample-status').textContent = '正在读取样例…'; try { const manifest = await loadSampleManifest('./assets/samples/manifest.json'); for (let index = 0; index < Math.min(5, manifest.frames.length); index++) { const frame = manifest.frames[index]; const response = await fetch(resolveSampleUrl(frame.path)); const blob = await response.blob(); await addFileToSlot(state, index, new File([blob], `${frame.id}.svg`, { type: blob.type || 'image/svg+xml' })); } renderSlots(); updateReady(); $('#sample-status').textContent = '样例已载入，可以直接生成相对深度。'; } catch (error) { showError(error); $('#sample-status').textContent = ''; } }
function reset() { client.cancel(); resetFrames(state); hideResult(); renderSlots(); updateReady(); $('#sample-status').textContent = ''; clearError(); }
function downloadBlob(blob, name) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 0); }
function activateMode(mode) { state.mode = mode; document.querySelectorAll('.mode-tab').forEach(tab => { const active = tab.dataset.mode === mode; tab.classList.toggle('active', active); tab.setAttribute('aria-selected', String(active)); }); $('#relative-panel').hidden = mode !== 'relative'; $('#intrinsics-panel').hidden = mode !== 'intrinsics'; $('#scale-panel').hidden = mode !== 'scale'; if (mode !== 'relative') hideResult(); }
function bind() {
  renderSlots(); updateReady(); $('#sample-button').addEventListener('click', useSample); $('#gallery-input').addEventListener('change', async event => { const files = [...(event.target.files || [])].slice(0, 5); resetFrames(state); for (let index = 0; index < files.length; index++) await addFileToSlot(state, index, files[index]); renderSlots(); updateReady(); }); $('#reset-button').addEventListener('click', reset); $('#again-button').addEventListener('click', reset); $('#run-button').addEventListener('click', runEstimate); $('#cancel-button').addEventListener('click', () => { client.cancel(); $('#progress-panel').hidden = true; showError(Object.assign(new Error('Cancelled'), { code: 'CANCELLED' })); }); document.querySelectorAll('.mode-tab').forEach(tab => tab.addEventListener('click', () => activateMode(tab.dataset.mode))); document.querySelectorAll('.view-tabs button').forEach(tab => tab.addEventListener('click', () => { document.querySelectorAll('.view-tabs button').forEach(item => item.classList.toggle('active', item === tab)); ['depth', 'confidence', 'middle'].forEach(kind => { $(`#${kind === 'depth' ? 'result' : kind === 'confidence' ? 'confidence' : 'middle'}-preview`).hidden = tab.dataset.view !== kind; }); })); $('#download-button').addEventListener('click', () => { if (!state.result) return; fetch($('#result-preview').src).then(response => response.blob()).then(blob => downloadBlob(blob, 'lab-005-relative-depth.png')); }); $('#download-json').addEventListener('click', () => { if (!state.result) return; downloadBlob(new Blob([JSON.stringify({ schema: 'lab005.depth-result.v1', width: state.result.width, height: state.result.height, depth: [...state.result.depth], confidence: [...state.result.confidence], invalid: [...state.result.invalid] }, null, 2)], { type: 'application/json' }), 'lab-005-depth.json'); }); $('#share-button').addEventListener('click', async () => { try { if (!navigator.share) throw new Error('share unavailable'); await navigator.share({ title: 'LAB 005 离焦测深', text: '五张焦点照片的相对深度结果' }); $('#share-status').textContent = '已打开系统分享。'; } catch { $('#share-status').textContent = '当前浏览器不支持系统分享，请使用下载按钮。'; } });
  $('#calibration-input').addEventListener('change', event => { $('#calibration-status').textContent = `已选择 ${event.target.files?.length || 0} 个标定视角，点击开始标定。`; }); $('#calibrate-button').addEventListener('click', async () => { const files = [...($('#calibration-input').files || [])]; if (files.length < 3) { $('#calibration-status').textContent = messageFor('CALIBRATION_FAILED'); return; } let frames = []; try { for (const file of files) { const decoded = await decodeFile(file); frames.push({ bitmap: decoded.bitmap, width: decoded.width, height: decoded.height }); } state.calibration = await client.run('calibrateIntrinsics', { frames, pattern: { cols: Number($('#pattern-cols').value), rows: Number($('#pattern-rows').value), squareSize: Number($('#square-size').value) } }); $('#calibration-status').textContent = `已接受 ${state.calibration.viewsAccepted} 个视角，覆盖率 ${(state.calibration.coverage * 100).toFixed(0)}%，倾角跨度 ${state.calibration.tiltSpanDeg}°。`; $('#download-calibration').disabled = false; } catch (error) { $('#calibration-status').textContent = messageFor(error.code); } finally { frames.forEach(frame => frame.bitmap?.close?.()); } }); $('#download-calibration').addEventListener('click', () => { if (state.calibration) downloadBlob(new Blob([JSON.stringify(state.calibration, null, 2)], { type: 'application/json' }), 'lab005-camera-intrinsics.json'); });
  $('#scale-input').addEventListener('change', event => { $('#scale-status').textContent = `已选择 ${event.target.files?.length || 0} 张照片。请确保三组距离各有五张。`; }); $('#scale-button').addEventListener('click', async () => { const distances = [1, 2, 3].map(index => Number($(`#distance-${index}`).value)); try { state.scaleCalibration = await client.run('calibrateScale', { samples: [0.1, 0.5, 0.9], distances }); $('#scale-status').textContent = '尺度拟合完成，结果标记为参考级。'; $('#download-scale').disabled = false; } catch (error) { $('#scale-status').textContent = messageFor(error.code); } }); $('#download-scale').addEventListener('click', () => { if (state.scaleCalibration) downloadBlob(new Blob([JSON.stringify(state.scaleCalibration, null, 2)], { type: 'application/json' }), 'lab005-focus-depth-scale.json'); }); }
bind();
$('#result-preview').addEventListener('click', event => {
  if (!state.result) return;
  const rect = event.currentTarget.getBoundingClientRect();
  const x = Math.max(0, Math.min(state.result.width - 1, Math.round((event.clientX - rect.left) / rect.width * state.result.width)));
  const y = Math.max(0, Math.min(state.result.height - 1, Math.round((event.clientY - rect.top) / rect.height * state.result.height)));
  const tile = Math.min(state.result.rows - 1, Math.floor(y / state.result.tileSize)) * state.result.cols + Math.min(state.result.cols - 1, Math.floor(x / state.result.tileSize));
  $('#sample-query').hidden = false;
  $('#query-value').textContent = state.result.invalid[tile] ? '该区域纹理不足' : `相对深度 ${(state.result.depth[tile] * 100).toFixed(0)}%，置信度 ${(state.result.confidence[tile] * 100).toFixed(0)}%`;
});
