export const available=(chapter,scene)=>chapter==='004'&&scene==='03';
export async function mount(host){
 host.innerHTML=`<h2>实拍照片的单目深度：Depth Anything V2 Small</h2><p>对照课件的明暗恢复：这里调用已发布的 LAB 007，通过 Transformers.js / ONNX Runtime 执行预训练模型，观察学习先验对真实照片的深度预测。它不是光度立体或 SFS 求解器。</p><p>运行界面内置室内、街道、人物实拍样例，也支持自己的图片。首次推理需下载约 27 MB 模型；输出为相对深度，没有米制标定和像素真值。</p><div class="real-actions"><button class="primary" data-depth-open>打开可运行实验</button><a href="https://hub-fover.github.io/Vision-Hu13/lab-007/" target="_blank" rel="noopener">独立窗口运行 ↗</a></div><p class="real-source">开源项目：<a href="https://github.com/DepthAnything/Depth-Anything-V2" target="_blank" rel="noopener">Depth Anything V2</a> · Small 模型 Apache-2.0；浏览器移植：<a href="https://github.com/huggingface/transformers.js" target="_blank" rel="noopener">Transformers.js</a>；<a href="https://github.com/hub-fover/Vision-Hu13/tree/main/lab-007" target="_blank" rel="noopener">本仓库 LAB 007 源码与照片来源</a>。</p><p>观察任务：比较物体颜色和深度的关系；寻找镜面、玻璃与遮挡边缘的预测失误。把预测结果与下方的明暗歧义实验对照，解释两种方法的假设差异。</p><div data-depth-frame></div>`;
 const preview=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption');img.src=new URL('../assets/depth/person.jpg',import.meta.url);img.alt='街道上的工匠，Depth Anything 真实照片样例';img.style.maxHeight='380px';caption.textContent='实拍样例：Wilfredor · Street Craftsman in Olinda · CC0；运行界面可选择同一人物照片。';preview.append(img,caption);host.querySelector('[data-depth-frame]').before(preview);
 let frame;host.querySelector('[data-depth-open]').onclick=()=>{
  if(frame)return;frame=document.createElement('iframe');frame.title='Depth Anything V2 Small 真实照片推理实验';frame.src='https://hub-fover.github.io/Vision-Hu13/lab-007/';frame.style.cssText='width:100%;height:820px;border:1px solid #bfd1e2;border-radius:12px;background:white';host.querySelector('[data-depth-frame]').append(frame);
 };
 return ()=>{if(frame){frame.src='about:blank';frame.remove();}};
}
