import {knn,trainHead,nms,normalize} from './models-core.mjs';
const base=new URL('./assets/models/',import.meta.url);
let runtime,modelPromise,cocoPromise;
function script(file){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=new URL(file,base);s.onload=resolve;s.onerror=()=>reject(Error(`本地依赖 ${file} 加载失败，请检查部署是否包含 real/assets/models`));document.head.append(s);});}
async function tfReady(){runtime??=script('tf.min.js').then(async()=>{await window.tf.ready();return window.tf;});try{return await runtime;}catch(e){runtime=null;throw e;}}
async function mobile(){modelPromise??=(async()=>{const tf=await tfReady(),net=await tf.loadLayersModel(new URL('mobilenet/model.json',base).href),embedding=tf.model({inputs:net.inputs,outputs:net.getLayer('global_average_pooling2d_1').output}),labels=await fetch(new URL('labels.json',base)).then(r=>r.json());return {tf,net,embedding,labels};})();try{return await modelPromise;}catch(e){modelPromise=null;throw e;}}
async function coco(){cocoPromise??=(async()=>{await tfReady();await script('coco-ssd.min.js');return window.cocoSsd.load({base:'lite_mobilenet_v2',modelUrl:new URL('coco/model.json',base).href});})();try{return await cocoPromise;}catch(e){cocoPromise=null;throw e;}}
export function available(chapter,scene){return chapter==='007'||(chapter==='008'&&['01','02'].includes(scene));}
export async function mount(host,{chapter,scene}){
 const detect=chapter==='008'&&scene==='02';let alive=true,ticket=0,busy=false,samples=[],last=null,current=detect?'person':'indoor',uploaded=null,inputReady=false,photoGeneration=0;
 host.innerHTML=`<h3>${detect?'COCO-SSD 真实照片目标检测':'MobileNet 真实照片分类与冻结特征训练'}</h3><p>${detect?'模型在浏览器实际执行，调整分数门限与二次 NMS；框的 IoU 用于抑制，不是检测准确率。':'ImageNet 预训练卷积网络提取 1024 维特征；自己标注两类照片，实际训练逻辑回归或 KNN。分类头训练不更新卷积网络。'}</p><div class="real-controls"><label>照片<select data-photo><option value="person" ${detect?'selected':''}>街头手工艺人 · CC0</option><option value="indoor" ${detect?'':'selected'}>客厅电视 · Pexels</option><option value="street">城市街道 · Pexels</option></select></label><label>本地照片<input data-upload type="file" accept="image/*"></label><label>${detect?'分数门限':'训练标签'}<select data-label>${detect?'<option value="0.15">0.15</option><option value="0.3" selected>0.30</option><option value="0.6">0.60</option>':'<option value="0">类别 A</option><option value="1">类别 B</option>'}</select></label><label>${detect?'二次 NMS IoU':'训练轮数'}<input data-param type="number" value="${detect?'.5':'150'}" min="${detect?'0':'10'}" max="${detect?'1':'1000'}" step="${detect?'.1':'10'}"></label></div><div class="real-actions"><button data-load>加载本地预训练模型</button><button data-run>运行真实推理</button>${detect?'':'<button data-add>提取并加入训练集</button><button data-train>训练分类头 / KNN</button>'}<button data-cancel>取消本次显示</button><button data-reset>重置训练集</button><button data-png>导出结果 PNG</button><button data-json>导出 JSON</button></div><p class="real-status" aria-live="polite"></p><progress hidden></progress><div class="real-grid"><figure><figcaption>输入真实照片</figcaption><canvas data-input width="640" height="425"></canvas></figure><figure><figcaption>${detect?'带坐标的预测框':'实际特征 / 损失 / 概率'}</figcaption><canvas data-process width="640" height="425"></canvas></figure><figure><figcaption>实际结果</figcaption><pre data-result>点击加载模型，再执行推理。上传图片仅在本地浏览器处理。</pre></figure></div><p class="real-source">开源来源：<a href="https://github.com/tensorflow/tfjs">TensorFlow.js 4.22.0</a> · <a href="https://github.com/tensorflow/tfjs-models/tree/master/${detect?'coco-ssd':'mobilenet'}">${detect?'COCO-SSD 2.2.3 / lite_mobilenet_v2':'MobileNet V1 alpha 1.0 / 224'}</a> · Apache-2.0；模型权重来自官方 Google Storage，已随页面本地部署。照片署名与许可：<a href="${new URL('photos.json',base).href}">来源台账</a>。ImageNet / COCO 标签未覆盖所有场景；微型自建训练集不能证明泛化能力。</p>`;
 const $=s=>host.querySelector(s),input=$('[data-input]'),output=$('[data-process]'),status=$('.real-status'),result=$('[data-result]'),progress=$('progress');
 function say(s){if(alive)status.textContent=s;}function show(value,snapshot={source:uploaded?'local upload':current,label:$('[data-label]').value,param:$('[data-param]').value}){$('[data-png]').disabled=!!value.modelLoaded;$('[data-json]').disabled=false;last={model:detect?'COCO-SSD lite_mobilenet_v2':'MobileNet V1 alpha 1.0',runtimeVersion:'4.22.0',modelPackageVersion:detect?'2.2.3':'legacy layers export',inputShape:detect?'dynamic RGB':[1,224,224,3],modelRevision:new URL(detect?'coco/model.json':'mobilenet/model.json',base).href,parameters:{labelOrScore:snapshot.label,epochsOrNms:snapshot.param},chapter,scene,input:snapshot.source,createdAt:new Date().toISOString(),...value};result.textContent=JSON.stringify(last,null,2);}
 function invalidateInput(){ticket++;inputReady=false;last=null;$('[data-png]').disabled=true;$('[data-json]').disabled=true;result.textContent='输入正在更新；旧结果已失效。';output.getContext('2d').clearRect(0,0,output.width,output.height);}
 async function photo(nextCurrent=current,nextUrl=null){const generation=++photoGeneration;invalidateInput();say('正在解码照片，请等待…');try{const img=new Image();img.src=nextUrl||new URL(nextCurrent+'.jpg',base).href;await img.decode();if(img.naturalWidth*img.naturalHeight>40000000)throw Error('照片超过 4000 万像素，请缩小后上传');if(!alive||generation!==photoGeneration){nextUrl&&URL.revokeObjectURL(nextUrl);return false;}const scale=Math.min(640/img.naturalWidth,480/img.naturalHeight);input.width=Math.round(img.naturalWidth*scale);input.height=Math.round(img.naturalHeight*scale);input.getContext('2d').drawImage(img,0,0,input.width,input.height);uploaded&&URL.revokeObjectURL(uploaded);uploaded=nextUrl;current=nextCurrent;inputReady=true;output.width=input.width;output.height=input.height;output.getContext('2d').drawImage(input,0,0);return true;}catch(e){nextUrl&&URL.revokeObjectURL(nextUrl);if(alive&&generation===photoGeneration){inputReady=false;input.getContext('2d').clearRect(0,0,input.width,input.height);say('照片加载失败：'+e.message+'。请选择有效照片后再运行。');}return false;}}

 function bars(values,title){output.width=640;output.height=425;const c=output.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,640,425);c.fillStyle='#16395b';c.font='16px sans-serif';c.fillText(title,12,24);const max=Math.max(...values.map(Math.abs),1e-9);values.slice(0,128).forEach((v,i)=>{c.fillStyle=v>=0?'#2474bb':'#ce6546';c.fillRect(12+i*610/Math.min(values.length,128),380,Math.max(2,610/Math.min(values.length,128)-1),-v/max*320);});}
 async function embedding(frame){const {tf,net,embedding,labels}=await mobile();const x=tf.tidy(()=>tf.browser.fromPixels(frame).resizeBilinear([224,224]).toFloat().div(127.5).sub(1).expandDims());try{const e=embedding.predict(x),p=net.predict(x);try{return {x:Array.from(await e.data()),top:Array.from(await p.data()).map((probability,i)=>({className:labels[i]||String(i),probability})).sort((a,b)=>b.probability-a.probability).slice(0,5)};}finally{e.dispose();p.dispose();}}finally{x.dispose();}}
 async function action(fn,requiresInput=true){if(busy)return;if(requiresInput&&!inputReady){say('照片未就绪或加载失败，请等待解码完成或重新选择有效照片。');return;}const snapshot={source:uploaded?'local upload':current,label:$('[data-label]').value,param:$('[data-param]').value,frame:document.createElement('canvas')};snapshot.frame.width=input.width;snapshot.frame.height=input.height;snapshot.frame.getContext('2d').drawImage(input,0,0);say('正在执行真实计算，请稍候…');busy=true;progress.hidden=false;const id=++ticket;try{if(!Number.isFinite(+snapshot.param)||!snapshot.param.trim())throw Error('请输入有效的数值参数');await fn(()=>alive&&id===ticket,snapshot);if(alive&&id===ticket)say(`完成 · ${detect?'COCO-SSD':'MobileNet'} · ${window.tf.getBackend()} 后端 · 训练照片 ${samples.length} 张`);}catch(e){if(alive&&id===ticket)say(`失败：${e.message}。检查本地模型文件是否完整；可重新点击加载，WebGL 不可用时刷新尝试 CPU 后端。`);}finally{busy=false;if(alive)progress.hidden=true;}}
 $('[data-photo]').onchange=async e=>{if(await photo(e.target.value))say('输入已更换；请重新推理。');};$('[data-upload]').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>20*1024*1024){photoGeneration++;invalidateInput();input.getContext('2d').clearRect(0,0,input.width,input.height);say('照片加载失败：请选择不超过 20 MB 的图片。');return;}if(await photo(current,URL.createObjectURL(file)))say('本地照片已载入；不会上传服务器。');};

 $('[data-load]').onclick=()=>action(async (valid,snapshot)=>{await(detect?coco():mobile());if(valid())show({modelLoaded:true,backend:window.tf.getBackend()},snapshot);},false);
 $('[data-run]').onclick=()=>action(async (valid,snapshot)=>{const start=performance.now();if(detect){const net=await coco(),candidates=await net.detect(snapshot.frame,100,.05);if(!valid())return;const detections=nms(candidates,Math.max(0,Math.min(1,+snapshot.param)),+snapshot.label);output.width=input.width;output.height=input.height;const c=output.getContext('2d');c.drawImage(input,0,0);c.font='16px sans-serif';for(const p of detections){c.strokeStyle='#00e4b4';c.lineWidth=3;c.strokeRect(...p.bbox);c.fillStyle='#003e36';c.fillRect(p.bbox[0],Math.max(0,p.bbox[1]-22),200,22);c.fillStyle='white';c.fillText(`${p.class} ${(p.score*100).toFixed(1)}%`,p.bbox[0]+3,Math.max(17,p.bbox[1]-5));}show({elapsedMs:performance.now()-start,detections,candidateCount:candidates.length,note:'候选已通过上游 COCO-SSD 内置 NMS，界面参数是二次同类 NMS；无真实标注，不报告 mAP / 准确率。'},snapshot);}else{const e=await embedding(snapshot.frame);if(!valid())return;bars(e.x,'MobileNet 全局平均池化特征：前 128 / 1024 维');show({elapsedMs:performance.now()-start,embeddingDimension:e.x.length,embeddingPreview:e.x.slice(0,16),imagenetTop5:e.top},snapshot);}});
 if(!detect){$('[data-add]').onclick=()=>action(async (valid,snapshot)=>{const e=await embedding(snapshot.frame);if(!valid())return;samples.push({x:e.x,y:+snapshot.label,source:snapshot.source});bars(e.x,'已加入训练集的真实照片特征');show({training:samples.map(({y,source})=>({y,source})),count:samples.length,warning:'同一照片多次加入不会产生独立样本；测试请上传另一张照片。'},snapshot);});$('[data-train]').onclick=()=>action(async (valid,snapshot)=>{const query=await embedding(snapshot.frame);if(!valid())return;const fit=trainHead(samples,Math.max(10,Math.min(1000,+snapshot.param))),p=fit.predict(query.x),near=knn(samples,query.x,Math.min(3,samples.length));bars(fit.losses,'实际分类头训练交叉熵（冻结卷积权重）');show({trainingCount:samples.length,embeddingDimension:query.x.length,linearProbabilityB:p,linearPrediction:p>=.5?'B':'A',knn:near,losses:fit.losses,trainAccuracy:samples.filter(s=>(fit.predict(s.x)>=.5?1:0)===s.y).length/samples.length,note:'这是训练集拟合率；当前照片可能属于训练集，不代表独立测试准确率。'},snapshot);});}
 $('[data-cancel]').onclick=()=>{ticket++;say('已取消结果显示；浏览器中的本次 GPU 计算可能仍会完成。');};$('[data-reset]').onclick=()=>{ticket++;samples=[];last=null;$('[data-png]').disabled=true;$('[data-json]').disabled=true;result.textContent='训练集已清空';say('训练集已重置。');output.getContext('2d').clearRect(0,0,output.width,output.height);};function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}$('[data-png]').onclick=()=>output.toBlob(b=>b&&download(b,'real-model-result.png'));$('[data-json]').onclick=()=>last&&download(new Blob([JSON.stringify(last,null,2)],{type:'application/json'}),'real-model-result.json');
 $('[data-png]').disabled=true;$('[data-json]').disabled=true;await photo();say('真实照片已载入。模型仅在点击按钮后加载，所有依赖与权重来自本站。');return()=>{alive=false;ticket++;photoGeneration++;uploaded&&URL.revokeObjectURL(uploaded);host.replaceChildren();};
}
