const asset=name=>new URL(`./assets/perception/${name}`,import.meta.url).href;
export const available=(chapter,scene)=>(String(chapter?.id??chapter)==='006'&&['01','02','04'].includes(String(scene?.id??scene)))||(String(chapter?.id??chapter)==='005'&&String(scene?.id??scene)==='03');
export async function mount(host,{chapter,scene}){
 const id=String(scene?.id??scene),segment=id==='04',flow=id==='02'||String(chapter?.id??chapter)==='005';let disposed=false,loading=false,worker=null,generation=0,result=null,runParams=null,snapshots=[],frames=[],names=[];
 host.innerHTML=`<p>${segment?'真实照片 RGB KMeans：每个像素分配到最近的颜色中心，再更新中心。':'真实视频帧：'+(flow?'FAST 特征 → 灰度金字塔 → Lucas–Kanade 稀疏光流。':'相邻帧逐像素 RGB 差值 → 阈值变化掩码。')}</p><div class="real-controls">${segment?'<label>颜色簇数 K <input data-k type="range" min="2" max="10" value="5"><output data-kout>5</output></label><label>迭代轮数 <input data-iterations type="range" min="1" max="25" value="10"><output data-iout>10</output></label>':flow?'<label>窗口尺寸 <select data-window><option>15</option><option selected>21</option><option>31</option></select></label><label>金字塔层数 <select data-levels><option>2</option><option selected>3</option><option>4</option></select></label><label>最大迭代 <input data-iterations type="range" min="5" max="40" value="30"><output data-iout>30</output></label>':'<label>变化阈值 <input data-threshold type="range" min="1" max="100" value="25"><output data-tout>25</output></label>'}</div><label>${segment?'上传本地照片':'上传两张按时间排序的视频帧（必须同尺寸）'}<input data-upload type="file" accept="image/*" ${segment?'':'multiple'}></label><div class="real-actions"><button data-run>运行真实图像实验</button><button data-cancel>取消</button><button data-default>恢复官方样例</button><label>中间阶段 <select data-stage></select></label><button data-png disabled>导出 PNG</button><button data-json disabled>导出 JSON</button></div><p class="real-status" role="status"></p><div class="real-views"><figure><figcaption>${segment?'输入照片':'前一帧 / FAST 特征'}</figcaption><canvas data-a></canvas></figure><figure><figcaption>${segment?'该轮簇颜色与像素分组':flow?'灰度金字塔 / 实际位移':'RGB 帧差'}</figcaption><canvas data-b></canvas></figure><figure><figcaption>${segment?'分割结果':flow?'后一帧 / 追踪结果':'阈值变化掩码'}</figcaption><canvas data-c></canvas></figure></div><p class="real-metrics"></p><pre data-log></pre><p class="real-source">${segment?'算法：本项目原创 RGB Lloyd KMeans 实现，未调用外部聚类库。照片：NASA / Eileen Collins，公有领域；由 scikit-image v0.19.3 分发。':'光流算法：实际调用 <a href="https://github.com/inspirit/jsfeat/tree/4c7b336bbeeb26e6cd4cdf3c7d414abe273846f3" target="_blank">inspirit/jsfeat</a>（MIT，固定提交 4c7b336）。帧差算法为本项目实现。真实帧：<a href="https://github.com/opencv/opencv/tree/4.10.0/samples/data" target="_blank">OpenCV 4.10.0 basketball1/2</a> 官方光流示例（随 Apache-2.0 仓库分发）。'} <a href="${asset('metadata.json')}" target="_blank">来源、许可证和 SHA-256</a>。${segment?'颜色聚类不等于语义分割。':'只有两帧，无多帧背景建模和目标身份标签；变化掩码不是目标真值。'} 本地上传与计算均在浏览器内进行。</p>`;
 const $=s=>host.querySelector(s),a=$('[data-a]'),b=$('[data-b]'),c=$('[data-c]'),status=$('.real-status');const canvases=[a,b,c];
 const loadingState=value=>{loading=value;$('[data-run]').disabled=value||!frames.length;host.querySelectorAll('.real-controls input,.real-controls select').forEach(e=>e.disabled=value)};const stop=()=>{generation++;worker?.terminate();worker=null;loadingState(false);$('[data-png]').disabled=$('[data-json]').disabled=true};const draw=(canvas,data)=>{canvas.width=data.width;canvas.height=data.height;canvas.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(data.data),data.width,data.height),0,0)};
 const overlay=(canvas,tracks,arrows=false)=>{const ctx=canvas.getContext('2d');ctx.lineWidth=1.6;for(const t of tracks){ctx.strokeStyle=t.valid?'#00ff8c':'#ff4169';ctx.beginPath();ctx.arc(arrows?t.nx:t.x,arrows?t.ny:t.y,3,0,7);ctx.stroke();if(arrows&&t.valid){ctx.beginPath();ctx.moveTo(t.x,t.y);ctx.lineTo(t.nx,t.ny);ctx.stroke()}}};
 const show=()=>{if(!frames.length)return;draw(a,frames[0]);if(segment){const s=snapshots[Number($('[data-stage]').value)||0];if(!s)return;const img={...frames[0],data:s.image};draw(c,img);b.width=frames[0].width;b.height=frames[0].height;const ctx=b.getContext('2d');s.centers.forEach((color,i)=>{const x=i*b.width/s.centers.length;ctx.fillStyle=`rgb(${color.map(Math.round).join(',')})`;ctx.fillRect(x,0,b.width/s.centers.length,b.height);ctx.fillStyle='#fff';ctx.fillText(`C${i+1}: ${s.counts[i]}`,x+4,20)});$('.real-metrics').textContent=`第 ${s.iteration} 轮 · RGB 均方误差 ${s.mse.toFixed(2)} · ${s.labels.length.toLocaleString()} 个真实像素`;return}if(!result)return;draw(c,frames[1]);if(flow){overlay(a,result.tracks);overlay(c,result.tracks,true);const p=result.pyramid[Number($('[data-stage]').value)||0];const rgba=new Uint8ClampedArray(p.data.length*4);p.data.forEach((v,i)=>{rgba[4*i]=rgba[4*i+1]=rgba[4*i+2]=v;rgba[4*i+3]=255});draw(b,{width:p.width,height:p.height,data:rgba});$('.real-metrics').textContent=`FAST 候选 ${result.detected} · LK 有效 ${result.tracked} · 红点为跟踪失败，无人工真值准确率`;}else{draw(b,{...frames[0],data:result.diff});draw(c,{...frames[0],data:result.image});$('.real-metrics').textContent=`变化像素 ${result.changed} / ${result.mask.length}（${(100*result.changed/result.mask.length).toFixed(1)}%）`;}};
 const load=async url=>{const img=new Image();img.src=url;await img.decode();if(img.width*img.height>24000000)throw Error('图片超过 2400 万像素，请缩小后上传');const scale=Math.min(1,384/img.width,288/img.height),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,canvas.width,canvas.height);return{originalWidth:img.width,originalHeight:img.height,width:canvas.width,height:canvas.height,data:ctx.getImageData(0,0,canvas.width,canvas.height).data}};
 const run=()=>{if(disposed||loading||!frames.length)return;stop();result=null;snapshots=[];$('[data-stage]').replaceChildren();$('[data-png]').disabled=$('[data-json]').disabled=true;status.textContent='计算中…';const token=generation;const source=`self.onmessage=async({data:d})=>{try{const m=await import(${JSON.stringify(new URL('./perception-core.mjs',import.meta.url).href)});if(d.segment){for(const s of m.kmeansSteps(d.frames[0].data,d.k,d.iterations)){self.postMessage({step:s});}}else if(d.flow){self.window=self;importScripts(${JSON.stringify(asset('jsfeat.js'))});const f=d.frames[0];self.postMessage({result:m.sparseFlow(self.jsfeat,f.data,d.frames[1].data,f.width,f.height,d)});}else self.postMessage({result:m.frameDifference(d.frames[0].data,d.frames[1].data,d.threshold)});self.postMessage({done:true});}catch(e){self.postMessage({error:e.message});}}`;const url=URL.createObjectURL(new Blob([source],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);worker.onmessage=({data})=>{if(disposed||token!==generation)return;if(data.error){status.textContent=`计算失败：${data.error}`;stop();return}if(data.step){snapshots.push(data.step);const o=document.createElement('option');o.value=snapshots.length-1;o.textContent=`第 ${data.step.iteration} 轮`; $('[data-stage]').append(o);$('[data-stage]').value=snapshots.length-1;show()}if(data.result){result=data.result;if(flow)result.pyramid.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`金字塔 ${i}: ${p.width}×${p.height}`;$('[data-stage]').append(o)});show()}if(data.done){status.textContent=`完成 · ${names.join(' / ')} · ${frames[0].width}×${frames[0].height} 工作尺寸`;$('[data-png]').disabled=$('[data-json]').disabled=false;$('[data-log]').textContent=segment?snapshots.map(s=>`迭代 ${s.iteration}: SSE=${s.sse.toFixed(0)}, MSE=${s.mse.toFixed(2)}`).join('\n'):'真实源图被等比例缩小用于浏览器计算。\n'+(flow?'FAST + 金字塔 LK；输出像素坐标与成功标志。':'RGB 通道绝对差均值，固定阈值二值化。');worker?.terminate();worker=null;}};worker.onerror=e=>{if(token===generation){status.textContent=`运行错误：${e.message}`;stop()}};runParams={k:Number($('[data-k]')?.value)||null,iterations:Number($('[data-iterations]')?.value)||null,window:Number($('[data-window]')?.value)||null,levels:Number($('[data-levels]')?.value)||null,threshold:Number($('[data-threshold]')?.value??20)};worker.postMessage({segment,flow,frames,...runParams});};
 if(!segment&&!flow){$('[data-stage]').disabled=true}const defaults=async()=>{stop();const token=generation;loadingState(true);status.textContent='加载本地真实样例…';const nextNames=segment?['NASA astronaut']:['OpenCV basketball1','OpenCV basketball2'];try{const f=await Promise.all((segment?['astronaut.png']:['basketball1.png','basketball2.png']).map(n=>load(asset(n))));if(disposed||token!==generation)return;frames=f;names=nextNames;loadingState(false);run()}catch(e){if(!disposed&&token===generation){loadingState(false);status.textContent=`图片加载失败：${e.message}`}}};
 $('[data-run]').onclick=run;$('[data-cancel]').onclick=()=>{stop();status.textContent='已取消，可重新运行'};$('[data-default]').onclick=defaults;$('[data-stage]').onchange=show;
 for(const [key,out] of [['k','kout'],['iterations','iout'],['threshold','tout']])if($(`[data-${key}]`))$(`[data-${key}]`).oninput=()=>{$(`[data-${out}]`).textContent=$(`[data-${key}]`).value};
 $('[data-upload]').onchange=async e=>{stop();const token=generation,files=[...e.target.files];if(files.length!==(segment?1:2)){status.textContent=segment?'请选择一张图片':'请选择两张视频帧';return}if(files.some(f=>!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>16*1024*1024)){status.textContent='请上传 PNG/JPEG/WebP，每张不超过 16 MiB';e.target.value='';return}loadingState(true);status.textContent='加载本地上传图片…';const urls=files.map(f=>URL.createObjectURL(f));try{const f=await Promise.all(urls.map(load));if(disposed||token!==generation)return;if(!segment&&(f[0].originalWidth!==f[1].originalWidth||f[0].originalHeight!==f[1].originalHeight||f[0].width!==f[1].width||f[0].height!==f[1].height))throw Error('两帧原始宽高必须一致');frames=f;names=files.map(f=>f.name);loadingState(false);run()}catch(e){if(!disposed&&token===generation){loadingState(false);status.textContent=e.message;e.target.value=''}}finally{urls.forEach(URL.revokeObjectURL)}};
 const download=(blob,name)=>{const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 $('[data-png]').onclick=()=>{const canvas=document.createElement('canvas');canvas.width=frames[0].width*3;canvas.height=frames[0].height;const ctx=canvas.getContext('2d');canvases.forEach((v,i)=>ctx.drawImage(v,i*frames[0].width,0,frames[0].width,frames[0].height));canvas.toBlob(blob=>blob&&download(blob,'perception-real.png'))};
 $('[data-json]').onclick=()=>{const data={version:'1.0.0',chapter:String(chapter?.id??chapter),scene:id,sources:names,inputDimensions:frames.map(f=>({width:f.originalWidth,height:f.originalHeight})),width:frames[0].width,height:frames[0].height,parameters:runParams,algorithm:segment?'original RGB Lloyd KMeans':flow?'jsfeat 4c7b336 FAST + pyramid LK':'original RGB frame difference',results:segment?snapshots.map(({iteration,sse,mse,centers,counts})=>({iteration,sse,mse,centers,counts})):flow?{tracks:result.tracks,detected:result.detected,tracked:result.tracked}:{changed:result.changed,mask:Array.from(result.mask)}};download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'perception-real.json')};
 await defaults();return()=>{disposed=true;stop();host.replaceChildren()};
}


