import {imageFrame,imageSequence,videoSequence,cameraStream,pixels} from './media-input.mjs';
const asset=name=>new URL(`./assets/temporal/${name}`,import.meta.url).href;
export async function mount(host,{chapter,scene}){
 const chapterId=String(chapter?.id??chapter),sceneId=String(scene?.id??scene),flow=chapterId==='005'||sceneId==='02';
 let disposed=false,epoch=0,controller=null,worker=null,stream=null,playTimer=null,liveTimer=null,busy=false,loading=false,frames=[],records=[],source=null,params=null,current=0,resolvePending=null,pendingInit=null;
 host.innerHTML=`<p>连续实拍实验：${flow?'FAST 特征 → 金字塔 LK → 前后向一致性筛选 → 固定特征 ID 与轨迹。':'相邻帧差 → 指数滑动平均背景 → 前景掩码 → 去噪与连通区域。'} 所有计算在本机进行。</p>
 <div class="real-controls"><label>采样帧率 <select data-fps><option>2</option><option selected>5</option><option>10</option></select></label><label>最大采样帧数 <select data-limit><option>30</option><option selected>80</option><option>120</option></select></label>
 ${flow?'<label>LK 窗口 <select data-window><option>15</option><option selected>21</option><option>31</option></select></label><label>金字塔层数 <select data-levels><option>2</option><option selected>3</option><option>4</option></select></label><label>前后向误差阈值(px) <input data-fb type="number" min="0.2" max="10" step="0.1" value="1.5"></label><label><input data-reseed type="checkbox" checked>失效后补充新角点</label>':'<label>变化阈值 <input data-threshold type="range" min="5" max="80" value="25"><output data-tout>25</output></label><label>背景更新率 α <input data-alpha type="number" min="0.001" max="1" step="0.01" value="0.03"></label><label>最小区域面积(px) <input data-area type="number" min="1" max="2000" value="25"></label><label><input data-freeze type="checkbox" checked>前景像素不更新背景</label><label><input data-clean type="checkbox" checked>3×3 开运算去噪</label>'}</div>
 <div class="real-controls"><label>导入连续图片（按文件名数字排序）<input data-upload type="file" accept="image/png,image/jpeg,image/webp" multiple></label><label>导入本地视频 MP4 / WebM<input data-video type="file" accept="video/*"></label></div>
 <div class="real-actions"><button data-default>恢复实拍样例</button><button data-run>运行连续实验</button><button data-cancel>取消处理</button></div>
 <details class="camera-panel"><summary>手机 / 电脑相机：实时拍照或视频</summary><div class="real-actions"><label>镜头 <select data-facing><option value="environment">后置</option><option value="user">前置</option></select></label><button data-camera>打开相机</button><button data-snap disabled>拍一帧</button><button data-live disabled>开始实时分析</button><button data-stop-camera disabled>关闭相机</button></div><video data-preview autoplay muted playsinline hidden></video><p>首次使用需要允许相机权限。连续拍摄两帧以上可回放；实时分析按采样帧率处理，忙碌时跳帧，最多保留最近 60 个结果。镜头切换会重新初始化轨迹或背景。手机浏览器编码支持可能不同。</p></details>
 <p class="real-status" role="status"></p><div class="sequence-timeline real-actions"><button data-prev disabled>上一帧</button><button data-play disabled>播放</button><button data-next disabled>下一帧</button><label>结果时间轴 <input data-time type="range" min="0" max="0" value="0" disabled></label><output data-time-label></output><label>回放速度 <select data-rate><option value=".5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option></select></label><button data-png disabled>导出当前 PNG</button><button data-json disabled>导出序列 JSON</button></div>
 ${flow?'':'<label><input data-mask type="checkbox">第三视图显示前景二值掩码</label>'}<div class="real-views"><figure><figcaption>${flow?'前一帧 / 本次跟踪起点':'相邻帧差掩码（对照）'}</figcaption><canvas data-a></canvas></figure><figure><figcaption>${flow?'当前帧 / 特征轨迹（绿：有效，红：失败）':'更新前的背景模型'}</figcaption><canvas data-b></canvas></figure><figure><figcaption>${flow?'当前帧 / 位移向量':'当前帧 / 前景连通区域'}</figcaption><canvas data-c></canvas></figure></div><p class="real-metrics"></p><figure><figcaption>${flow?'有效跟踪数与失效数随时间变化（绿 / 红）':'背景前景比例与相邻帧差比例（蓝 / 红）'}</figcaption><canvas data-curve class="sequence-curve"></canvas></figure><pre data-log></pre>
 <details open><summary>深入观察与实验任务</summary><p>${flow?'① 比较 2/5/10 fps：帧间位移变大时哪些角点先丢失？② 开关角点补充：观察轨迹寿命与新 ID，补点不表示原目标重新识别。③ 将前后向阈值从 1.5 调至 0.5，比较保留率与误差；来回一致不保证语义正确。④ 用手机先固定镜头再移动镜头，比较背景与行人轨迹。':'① 固定相机拍移动物体，比较帧差与背景前景。② 关闭“前景不更新背景”，提高 α，停住物体，观察被背景吸收。③ 比较开运算前后的小区域消失。④ 移动镜头或改变照明，观察整幅画面被误判，解释固定相机假设。'}</p><p>${flow?'ID 属于图像特征，不属于人或物体。速度为工作图像像素/秒，不能解释为真实物理速度；图片序列的秒数由你设置的帧率决定。':'连通框标出变化区域，不是人员检测框；背景首帧可能包含人，不能当作空场景真值。'} 无人工标注时不显示准确率。</p></details>
 <p class="real-source">真实样例：<a href="https://github.com/opencv/opencv/blob/4.10.0/samples/data/vtest.avi" target="_blank">OpenCV 4.10.0 vtest.avi</a> 前 6 秒行人实拍片段（缩小、抽帧，无合成帧）；算法使用 <a href="https://github.com/inspirit/jsfeat" target="_blank">JSFeat</a> 固定提交的 LK，时序、背景与连通区域由本项目实现。<a href="${asset('metadata.json')}" target="_blank">素材来源、时间戳与 SHA-256</a></p>`;
 const $=s=>host.querySelector(s),status=$('.real-status'),preview=$('[data-preview]'),canvases=[$('[data-a]'),$('[data-b]'),$('[data-c]')];
 function pause(){clearTimeout(playTimer);playTimer=null;$('[data-play]').textContent='播放'}
 function cameraOff(){clearInterval(liveTimer);liveTimer=null;stream?.getTracks().forEach(t=>t.stop());stream=null;preview.pause();preview.srcObject=null;preview.hidden=true;$('[data-snap]').disabled=$('[data-live]').disabled=$('[data-stop-camera]').disabled=true;$('[data-live]').textContent='开始实时分析'}
 function cancel(){epoch++;controller?.abort();controller=null;worker?.terminate();worker=null;pendingInit?.(new DOMException('已取消','AbortError'));pendingInit=null;resolvePending?.(null);resolvePending=null;busy=false;loading=false;pause();cameraOff();controls();}
 function controls(){const ready=records.length>0;for(const key of ['prev','next','play','time','png','json'])$(`[data-${key}]`).disabled=!ready;$('[data-run]').disabled=loading||!!liveTimer||frames.length<2;}
 function reset(){records=[];current=0;$('[data-time]').max='0';$('[data-time]').value='0';$('.real-metrics').textContent='';$('[data-log]').textContent='';$('[data-time-label]').textContent='';$('[data-curve]').getContext('2d').clearRect(0,0,640,140);controls()}
 function options(){return {mode:flow?'flow':'background',window:Number($('[data-window]')?.value)||21,levels:Number($('[data-levels]')?.value)||3,fb:Math.max(.2,Math.min(10,Number($('[data-fb]')?.value)||1.5)),threshold:Number($('[data-threshold]')?.value)||25,alpha:Math.max(.001,Math.min(1,Number($('[data-alpha]')?.value)||.03)),minArea:Math.max(1,Math.min(2000,Number($('[data-area]')?.value)||25)),freeze:$('[data-freeze]')?.checked??true,clean:$('[data-clean]')?.checked??true,reseed:$('[data-reseed]')?.checked??true}}
 function draw(canvas,data,w,h){canvas.width=w;canvas.height=h;canvas.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(data),w,h),0,0)}
 function show(){if(!records.length)return;current=Math.min(records.length-1,Math.max(0,current));const r=records[current],{width:w,height:h,metrics:m}=r;
  draw(canvases[0],flow?r.previous:r.frameDiff,w,h);draw(canvases[1],flow?r.current:r.background,w,h);draw(canvases[2],!flow&&$('[data-mask]')?.checked?r.image:r.current,w,h);
  if(flow){for(const t of r.tracks){for(const [i,canvas] of canvases.entries()){const ctx=canvas.getContext('2d');ctx.strokeStyle=t.valid?'#00ed8c':'#ef3340';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=1.4;if(i===0){ctx.beginPath();ctx.arc(t.x,t.y,2,0,7);ctx.stroke()}else if(i===1){ctx.beginPath();t.history.forEach(([x,y],j)=>j?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();if(t.valid){ctx.fillRect(t.nx-2,t.ny-2,4,4);if(t.id%10===0)ctx.fillText(t.id,t.nx+3,t.ny)}}else if(t.valid){ctx.beginPath();ctx.moveTo(t.x,t.y);ctx.lineTo(t.nx,t.ny);ctx.stroke();ctx.fillRect(t.nx-1,t.ny-1,3,3)}}}
   $('.real-metrics').textContent=`有效 ${m.active}/${m.tested} · 失效 ${m.lost} · 保留率 ${(100*m.retention).toFixed(1)}% · 中值位移 (${m.medianDx.toFixed(2)}, ${m.medianDy.toFixed(2)}) px · ${m.medianSpeed.toFixed(2)} px/s · 前后向误差 ${m.medianFB.toFixed(3)} px · 新角点 ${m.added}`;
  }else{const ctx=canvases[2].getContext('2d');ctx.strokeStyle='#00eb8b';ctx.lineWidth=2;for(const b of r.boxes)ctx.strokeRect(b.x,b.y,b.width,b.height);$('.real-metrics').textContent=`帧差 ${(100*m.changed/(w*h)).toFixed(1)}% · 背景前景 ${(100*m.foreground/(w*h)).toFixed(1)}% · 连通区域 ${m.regions} · α=${params.alpha} · ${params.freeze?'排除前景更新':'全部像素更新'}`;}
  $('[data-time]').value=current;$('[data-time-label]').textContent=`结果 ${current+1}/${records.length} · ${r.time.toFixed(2)}s · Δt=${r.dt.toFixed(3)}s`;
  const curve=$('[data-curve]');curve.width=640;curve.height=140;const ctx=curve.getContext('2d');ctx.fillStyle='#f6f9fc';ctx.fillRect(0,0,640,140);let max=flow?Math.max(1,...records.map(x=>x.metrics.tested)):1;
  for(let series=0;series<2;series++){ctx.strokeStyle=series?'#db4d50':flow?'#008b61':'#146be8';ctx.beginPath();records.forEach((x,i)=>{const v=flow?(series?x.metrics.lost:x.metrics.active):(series?x.metrics.changed:x.metrics.foreground)/(x.width*x.height),px=10+i*620/Math.max(1,records.length-1),py=130-v/max*115;i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke()}ctx.strokeStyle='#334155';const cursor=10+current*620/Math.max(1,records.length-1);ctx.beginPath();ctx.moveTo(cursor,0);ctx.lineTo(cursor,140);ctx.stroke();
  $('[data-log]').textContent=`输入：${source?.names?.join(', ')??'相机'}\n${source?.timeBasis??''} · 工作尺寸 ${w}×${h}\n${flow?'红色点是实际 LK / 前后向筛选失败，不表示物体消失。':'前景掩码与框是变化区域；第一幅背景直接由首帧初始化。'}\n${source?.truncated?'达到采样上限；仅处理视频前段。':''}`;
 }
 async function init(token){params=options();worker=new Worker(new URL('./temporal.worker.mjs',import.meta.url));return new Promise((resolve,reject)=>{pendingInit=reject;worker.onmessage=({data})=>{if(token!==epoch||disposed)return;if(data.error){resolvePending?.(null);resolvePending=null;pendingInit=null;reject(Error(data.error));status.textContent=`计算失败：${data.error}；请重新开始实时分析或重新加载输入`;worker?.terminate();worker=null;clearInterval(liveTimer);liveTimer=null;$('[data-live]').textContent='开始实时分析';busy=false;loading=false;controls()}else if(data.ready){pendingInit=null;resolve();}else if(data.done){const done=resolvePending;resolvePending=null;busy=false;if(data.result){if(!flow){delete data.result.previous;delete data.result.diff;}records.push(data.result);if(liveTimer&&records.length>60)records.shift();current=records.length-1;$('[data-time]').max=records.length-1;show();controls()}done?.(data.result)}};worker.onerror=e=>{resolvePending?.(null);resolvePending=null;busy=false;loading=false;worker?.terminate();worker=null;clearInterval(liveTimer);liveTimer=null;$('[data-live]').textContent='开始实时分析';controls();status.textContent=`计算失败：${e.message}`;pendingInit=null;reject(Error(e.message));};worker.postMessage({type:'init',options:params})})}
 function push(frame){if(!worker||busy)return Promise.resolve(null);busy=true;return new Promise(resolve=>{resolvePending=resolve;worker.postMessage({type:'frame',frame})})}
 async function run(){if(loading||frames.length<2||disposed)return;cancel();reset();const token=epoch;loading=true;controls();status.textContent='计算连续帧…';try{await init(token);for(let i=0;i<frames.length;i++){if(token!==epoch||disposed)return;await push(frames[i]);if(!worker)return;status.textContent=`计算 ${i+1}/${frames.length}`}if(token!==epoch)return;loading=false;controls();status.textContent=`完成 · ${frames.length} 帧 · ${records.length} 个连续结果`;}catch(e){if(token===epoch){loading=false;controls();status.textContent=`计算失败：${e.message}`}}}
 async function loadInput(factory){cancel();reset();frames=[];const token=epoch;controller=new AbortController();loading=true;controls();status.textContent='加载连续真实帧…';try{const data=await factory({fps:Number($('[data-fps]').value),limit:Number($('[data-limit]').value),signal:controller.signal,progress:(n,total)=>{if(token===epoch)status.textContent=`解码 ${n}/${total}`}});if(token!==epoch||disposed)return;frames=data.frames;source={...data,frames:undefined,inputDimensions:{width:data.frames[0].originalWidth,height:data.frames[0].originalHeight}};loading=false;draw(canvases[0],frames[0].data,frames[0].width,frames[0].height);await run()}catch(e){if(token===epoch&&!disposed){loading=false;controls();status.textContent=`加载失败：${e.message}`}}}
 const defaults=()=>loadInput(async({signal,progress})=>{const meta=await fetch(asset('metadata.json'),{signal}).then(r=>r.json()),out=[];for(const f of meta.frames){out.push(await imageFrame(asset(f.file),f.time,signal));progress(out.length,meta.frames.length)}return {frames:out,names:['OpenCV vtest 前6秒'],kind:'sample',fps:5,timeBasis:'原视频10 fps，每2帧抽样',source:meta.source}});
 $('[data-default]').onclick=defaults;$('[data-run]').onclick=run;$('[data-cancel]').onclick=()=>{cancel();status.textContent='已取消；相机已关闭。可重新运行已加载的序列'};
 $('[data-upload]').onchange=e=>{const files=[...e.target.files];if(files.length)loadInput(o=>imageSequence(files,o))};$('[data-video]').onchange=e=>{const file=e.target.files[0];if(file)loadInput(o=>videoSequence(file,o))};
 if($('[data-mask]'))$('[data-mask]').onchange=show;if($('[data-threshold]'))$('[data-threshold]').oninput=()=>{$('[data-tout]').textContent=$('[data-threshold]').value};
 function step(delta){pause();current+=delta;show()}$('[data-prev]').onclick=()=>step(-1);$('[data-next]').onclick=()=>step(1);$('[data-time]').oninput=e=>{pause();current=Number(e.target.value);show()};
 $('[data-play]').onclick=()=>{if(playTimer){pause();return}if(current===records.length-1)current=0;$('[data-play]').textContent='暂停';const tick=()=>{show();if(current>=records.length-1){pause();return}const delay=Math.max(25,1000*records[current+1].dt/Number($('[data-rate]').value));playTimer=setTimeout(()=>{current++;tick()},delay)};tick()};
 async function openCamera(){cancel();reset();frames=[];source={kind:'camera',names:['本地相机'],timeBasis:'本机 performance.now 单调时钟'};const token=epoch;status.textContent='等待相机权限…';try{const next=await cameraStream($('[data-facing]').value);if(token!==epoch||disposed){next.getTracks().forEach(t=>t.stop());return}stream=next;preview.srcObject=stream;preview.hidden=false;status.textContent='已获得相机权限，等待画面…';let cameraTimeout;try{await Promise.race([preview.play(),new Promise((_,reject)=>{cameraTimeout=setTimeout(()=>reject(Error('相机画面加载超时，请关闭后重新打开')),12000)})])}finally{clearTimeout(cameraTimeout)};if(token!==epoch||disposed)return;$('[data-snap]').disabled=$('[data-live]').disabled=$('[data-stop-camera]').disabled=false;status.textContent='相机已打开：拍摄两帧以上，或开始实时分析。';}catch(e){if(token===epoch){cameraOff();status.textContent=e.message}}}
 $('[data-camera]').onclick=openCamera;$('[data-facing]').onchange=()=>{if(stream)openCamera()};$('[data-stop-camera]').onclick=()=>{cancel();status.textContent='相机已关闭；保留已计算结果供回放与导出'};
 $('[data-snap]').onclick=()=>{if(!stream||liveTimer)return;if(!frames.length){epoch++;worker?.terminate();worker=null;pendingInit?.(new DOMException('已取消','AbortError'));pendingInit=null;resolvePending?.(null);resolvePending=null;busy=false;reset()}try{const f=pixels(preview,performance.now()/1000);if(frames[0]&&(f.width!==frames[0].width||f.height!==frames[0].height))throw Error('相机尺寸改变，请重新打开相机');frames.push(f);if(frames.length>120)frames.shift();draw(canvases[0],f.data,f.width,f.height);status.textContent=`已拍摄 ${frames.length} 帧；关闭相机后运行连续实验`;controls()}catch(e){status.textContent=e.message}};
 $('[data-live]').onclick=async()=>{if(liveTimer){clearInterval(liveTimer);liveTimer=null;$('[data-live]').textContent='开始实时分析';loading=false;controls();status.textContent='实时分析已暂停，可回放结果';return}if(!stream||!preview.videoWidth)return;pause();epoch++;worker?.terminate();resolvePending?.(null);resolvePending=null;busy=false;reset();frames=[];const token=epoch;$('[data-live]').disabled=true;try{await init(token);if(token!==epoch)return;const start=performance.now();let count=0,skipped=0;liveTimer=setInterval(async()=>{if(busy||!stream){skipped++;return}try{const f=pixels(preview,(performance.now()-start)/1000);await push(f);if(!worker||!liveTimer||token!==epoch)return;if(token===epoch){status.textContent=`实时处理中 · ${++count} 帧 · 忙碌跳帧 ${skipped} · 最新 ${records.length} 个结果`}}catch(e){clearInterval(liveTimer);liveTimer=null;status.textContent=e.message;controls()}},1000/Number($('[data-fps]').value));$('[data-live]').textContent='暂停实时分析';$('[data-live]').disabled=false;controls()}catch(e){if(token===epoch){$('[data-live]').disabled=!stream;status.textContent=e.message}}};
 const download=(blob,name)=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 $('[data-png]').onclick=()=>{show();const r=records[current],c=document.createElement('canvas');c.width=r.width*3;c.height=r.height;canvases.forEach((v,i)=>c.getContext('2d').drawImage(v,i*r.width,0));c.toBlob(b=>b&&download(b,'continuous-real.png'))};
 $('[data-json]').onclick=()=>{const data={version:'2.0.0',chapter:chapterId,scene:sceneId,source,parameters:params,workSize:records[0]?{width:records[0].width,height:records[0].height}:null,selectedResult:current,records:records.map(({index,time,dt,originalWidth,originalHeight,metrics,tracks,boxes})=>({index,time,dt,inputDimensions:{width:originalWidth,height:originalHeight},metrics,tracks,boxes}))};download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'continuous-real.json')};
 void defaults();return()=>{disposed=true;cancel();host.replaceChildren()};
}
