import { test, expect } from '@playwright/test';
test('measurement tool starts with sample and no horizontal overflow',async({page})=>{await page.goto('./');await expect(page.getByRole('button',{name:'用样例体验'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);});
test('sample produces chart, frequency and download actions',async({page})=>{await page.goto('./');await page.getByRole('button',{name:'用样例体验'}).click();await expect(page.locator('#metricFrequency')).not.toHaveText('—');await expect(page.locator('#downloadJson')).toBeEnabled();});
test('结果视频：sample result includes an annotated video relative to the initial frame',async({page})=>{await page.goto('./');await page.getByRole('button',{name:'用样例体验'}).click();await expect(page.locator('#metricFrequency')).not.toHaveText('—');const video=page.locator('#motionVideo');await expect(video).toBeVisible();await expect(video).toHaveAttribute('src',/./);await expect(page.locator('#downloadVideo')).toBeEnabled();await expect(page.locator('body')).toContainText('相对于初始帧');await expect(page.locator('body')).toContainText('Δx');await expect(page.locator('body')).toContainText('Δy');await expect(page.locator('body')).toContainText('位移');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);});
test('camera permission failure gives local recovery text',async({page})=>{await page.goto('./');await page.getByRole('button',{name:'实时测量'}).click();await page.getByRole('button',{name:'开始后置相机'}).click();await expect(page.locator('#liveStatus')).toContainText(/权限|支持|HTTPS/);});
test('editor supports touch-friendly ROI and scale modes',async({page})=>{await page.goto('./');await page.getByRole('button',{name:'用样例体验'}).click();const canvas=page.locator('#targetCanvas');await page.getByRole('button',{name:'设置两点标尺'}).click();await expect(page.locator('#scaleMode')).toHaveAttribute('aria-pressed','true');await expect(page.locator('#editorHint')).toContainText('点击设置');await page.getByRole('button',{name:'调整目标框'}).click();await expect(page.locator('#roiMode')).toHaveAttribute('aria-pressed','true');await expect(page.locator('#editorHint')).toContainText('拖动四角');const box=await canvas.boundingBox();if(!box)throw new Error('editor canvas missing');await page.mouse.move(box.x+box.width*.45,box.y+box.height*.35);await page.mouse.down();await page.mouse.move(box.x+box.width*.48,box.y+box.height*.38);await page.mouse.up();});
test('professional path imports a local photo sequence',async({page})=>{await page.goto('./');await page.locator('#fileInput').setInputFiles(['tests/fixtures/texture.svg','tests/fixtures/texture.svg']);await expect(page.locator('#setupState')).toContainText('2 帧');await expect(page.locator('#status')).toContainText('2 张照片');});
test('switching from sample to live does not reuse the sample measurement',async({page})=>{await page.goto('./');await page.getByRole('button',{name:'用样例体验'}).click();await expect(page.locator('#downloadJson')).toBeEnabled();await page.getByRole('button',{name:'实时测量'}).click();await expect(page.locator('#measureButton')).toBeDisabled();await expect(page.locator('#setupChecklist')).toContainText('加载样例');await expect(page.locator('#downloadJson')).toBeDisabled();});
test('roi corner follows the complete multi-step drag on touch-sized canvas',async({page})=>{await page.goto('./');await page.getByRole('button',{name:'用样例体验'}).click();const canvas=page.locator('#targetCanvas');await canvas.scrollIntoViewIfNeeded();const box=await canvas.boundingBox();if(!box)throw new Error('editor canvas missing');const border=()=>page.evaluate(()=>{const canvas=document.querySelector('#targetCanvas'),data=canvas.getContext('2d').getImageData(0,0,640,360).data,points=[];for(let y=0;y<360;y++)for(let x=0;x<640;x++){const i=(y*640+x)*4;if(data[i]===130&&data[i+1]===228&&data[i+2]===210)points.push([x,y]);}return {minX:Math.min(...points.map(([x])=>x)),maxX:Math.max(...points.map(([x])=>x))};});const before=await border();const sx=box.width/640,sy=box.height/360;const start={x:box.x+220*sx,y:box.y+110*sy};await page.mouse.move(start.x,start.y);await page.mouse.down();for(let step=1;step<=5;step++){await page.mouse.move(start.x-70*sx*step/5,start.y-45*sy*step/5);await page.waitForTimeout(20);}await page.mouse.up();const after=await border();expect(after.minX).toBeLessThan(before.minX-50);expect(after.maxX).toBe(before.maxX);});
