import { test, expect } from '@playwright/test';

test('首屏只讲静止世界反算手机速度', async ({ page }) => { await page.goto('./'); await expect(page.getByRole('heading', { name: /拿手机对着静止物/ })).toBeVisible(); await expect(page.locator('body')).toContainText('不靠 GPS'); await expect(page.locator('body')).not.toContainText(/振动频率|飞机测速|毫米位移|DIC/); });
test('确定性样例输出参考级速度和诊断', async ({ page }) => { await page.goto('./'); await page.getByRole('button', { name: '用样例体验' }).click(); await expect(page.locator('#status')).toContainText('参考级表观速度'); await expect(page.locator('#metricVelocity')).not.toHaveText('—'); await expect(page.locator('#metricMeanSpeed')).not.toHaveText('—'); await expect(page.locator('#metricValid')).toContainText('%'); await page.getByText('高级诊断').click(); await expect(page.locator('#diagnosticsText')).toContainText('inlierRatio'); await expect(page.locator('#downloadJson')).toBeEnabled(); });
test('实时后置相机为主且权限失败可导入视频', async ({ page }) => { await page.goto('./'); await page.getByRole('button', { name: '实时后置相机' }).click(); await page.getByRole('button', { name: '开始后置相机' }).click(); await expect(page.locator('#liveStatus')).toContainText(/权限|视频|相机/); await expect(page.getByText('导入视频备用')).toBeVisible(); });
test('三种挑战都可见', async ({ page }) => { await page.goto('./'); await expect(page.getByRole('button', { name: '慢速移动' })).toBeVisible(); await expect(page.getByRole('button', { name: '快速移动' })).toBeVisible(); await expect(page.getByRole('button', { name: '不同环境' })).toBeVisible(); });
test('尺度为零时禁止测速', async ({ page }) => { await page.goto('./'); await page.getByRole('button', { name: '用样例体验' }).click(); await page.locator('#scaleInput').fill('0'); await expect(page.locator('#scaleInput')).toHaveAttribute('aria-invalid', 'true'); await expect(page.locator('#measureButton')).toBeDisabled(); });
test('切换模式清除旧结果', async ({ page }) => { await page.goto('./'); await page.getByRole('button', { name: '用样例体验' }).click(); await expect(page.locator('#downloadJson')).toBeEnabled(); await page.getByRole('button', { name: '实时后置相机' }).click(); await expect(page.locator('#measureButton')).toBeDisabled(); });
test('桌面与手机视口没有横向溢出', async ({ page }) => { await page.goto('./'); expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true); });
test('页面说明主要失败边界', async ({ page }) => { await page.goto('./'); await expect(page.locator('.boundary-panel')).toContainText('动态背景'); await expect(page.locator('.boundary-panel')).toContainText('纹理不足'); await expect(page.locator('.boundary-panel')).toContainText('急转'); });
