import {N,grid,heat,curves,scatter,rmse,ls,solve,rng,control as c,scene,result,stage} from './geometry-numeric.mjs';
const file='005-三维重建2.pptx',make=(id,title,pages,controls,compute,goal,principle,steps,questions,failure)=>scene(id,title,pages,controls,compute,goal,principle,steps,questions,failure,file);
export const scenes=[
make('01','透视投影、畸变与标定','3–23',[c('focal','焦距（像素）',200,1000,20,500),c('distortion','径向畸变 k₁',-.4,.4,.02,.12)],({params:p})=>{const pts=Array.from({length:49},(_,i)=>[(i%7-3)*.2,(Math.floor(i/7)-3)*.2,2+.05*(i%5)]),ideal=pts.map(([x,y,z])=>[p.focal*x/z,p.focal*y/z]),dist=pts.map(([x,y,z])=>{const r=(x*x+y*y)/(z*z),s=1+p.distortion*r;return [p.focal*x/z*s,p.focal*y/z*s];}),rows=[],b=[];pts.forEach(([x,y,z],i)=>{const r=(x*x+y*y)/(z*z);rows.push([x/z,x/z*r],[y/z,y/z*r]);b.push(...dist[i]);});const [f,fk]=ls(rows,b),k=fk/f,reproj=pts.map(([x,y,z])=>{const s=1+k*(x*x+y*y)/(z*z);return [f*x/z*s,f*y/z*s];}),res=dist.map((v,i)=>Math.hypot(v[0]-reproj[i][0],v[1]-reproj[i][1])),views=[scatter('理想针孔投影',ideal),scatter('带径向畸变观测',dist),scatter('拟合标定重投影',reproj)];return result(views,[stage('针孔到畸变',[views[0],views[1],{kind:'bars',title:'畸变位移',values:dist.map((v,i)=>Math.hypot(v[0]-ideal[i][0],v[1]-ideal[i][1]))}]),stage('最小二乘拟合',views)],{'估计焦距':f,'估计 k₁':k,'重投影 RMSE':Math.sqrt(res.reduce((s,v)=>s+v*v,0)/res.length)},{focal:f,k,focalError:Math.abs(f-p.focal),residuals:res,points:pts});},'理解透视除法和径向畸变，拟合受约束的相机参数。','已知三维标靶及姿态时，u=f x/z + (fk₁)xr²/z 是线性最小二乘。',['改变焦距检查尺度。','改变畸变系数。','比较拟合重投影与观测。'],['为什么一般标定需要多姿态？','图像中心附近能约束畸变吗？'],'固定主点、已知姿态且无切向畸变；不是完整 Zhang 多视图标定。'),
make('02','极线几何与三角测量','25–42',[c('baseline','双目基线',.1,1,.05,.4),c('focal','焦距（像素）',200,1000,20,500),c('noise','匹配噪声（像素）',0,2,.1,0)],({params:p,seed})=>{const random=rng(seed),pts=Array.from({length:35},(_,i)=>[(i%7-3)*.18,(Math.floor(i/7)-2)*.16,2+(i%6)*.3]),a=pts.map(([x,y,z])=>[p.focal*x/z,p.focal*y/z]),b=pts.map(([x,y,z])=>[p.focal*(x-p.baseline)/z+p.noise*(random()-.5),p.focal*y/z+p.noise*(random()-.5)]),z=a.map((v,i)=>p.focal*p.baseline/Math.max(.001,v[0]-b[i][0])),truth=pts.map(q=>q[2]),F=[[0,0,0],[0,0,-p.baseline/p.focal],[0,p.baseline/p.focal,0]],res=a.map((v,i)=>p.baseline/p.focal*(v[1]-b[i][1])),views=[scatter('左图匹配点',a),scatter('右图及水平极线',b,a.map(v=>[-180,v[1],180,v[1]])),scatter('三角化 X–Z',z.map((v,i)=>[a[i][0]*v/p.focal,v]))];return result(views,[stage('极线约束',[views[0],views[1],{kind:'bars',title:'x₂ᵀ F x₁',values:res}]),stage('视差三角化',views)],{'深度 RMSE':rmse(z,truth),'平均极线残差':res.reduce((s,v)=>s+Math.abs(v),0)/res.length},{rmse:rmse(z,truth),depth:z,truth,F,epipolarResidual:res});},'验证极线约束，观察视差到深度的误差放大。','平行校正双目具有水平极线；F=K⁻ᵀ[t]×K⁻¹，深度 Z=fB/d。',['改变基线观察视差。','引入匹配噪声。','比较远近点的深度误差。'],['基线过小有什么后果？','为什么极线不能保证对应唯一？'],'已知平行双目外参；未估计一般基础矩阵；重复纹理和遮挡匹配不在此模拟内。'),
make('03','Lucas–Kanade 光流','44–63',[c('dx','水平平移（像素）',-.8,.8,.1,.35),c('dy','垂直平移（像素）',-.8,.8,.1,-.25),c('iterations','迭代次数',1,12,1,6)],({params:p,input})=>{const analytic=(x,y)=>.5+.16*Math.sin(x*.42)+.16*Math.cos(y*.36)+.1*Math.sin((x+y)*.28);let sample=analytic;if(input){sample=(x,y)=>{const xx=Math.max(0,Math.min(input.width-1,x/(N-1)*(input.width-1))),yy=Math.max(0,Math.min(input.height-1,y/(N-1)*(input.height-1))),ix=Math.floor(xx),iy=Math.floor(yy),tx=xx-ix,ty=yy-iy,at=(a,b)=>input.data[Math.min(input.height-1,b)*input.width+Math.min(input.width-1,a)];return at(ix,iy)*(1-tx)*(1-ty)+at(ix+1,iy)*tx*(1-ty)+at(ix,iy+1)*(1-tx)*ty+at(ix+1,iy+1)*tx*ty;};}const first=grid(sample),second=grid((x,y)=>sample(x-p.dx,y-p.dy));let u=0,v=0,loss=[],stages=[],rank=2,observability=1;for(let t=0;t<p.iterations;t++){const rows=[],b=[];let e=0;for(let y=3;y<N-3;y++)for(let x=3;x<N-3;x++){const r=sample(x+u-p.dx,y+v-p.dy)-sample(x,y),gx=(sample(x+u-p.dx+.1,y+v-p.dy)-sample(x+u-p.dx-.1,y+v-p.dy))/.2,gy=(sample(x+u-p.dx,y+v-p.dy+.1)-sample(x+u-p.dx,y+v-p.dy-.1))/.2;rows.push([gx,gy]);b.push(-r);e+=r*r;}const aa=rows.reduce((s,r)=>s+r[0]*r[0],0),ab=rows.reduce((s,r)=>s+r[0]*r[1],0),bb=rows.reduce((s,r)=>s+r[1]*r[1],0),disc=Math.hypot(aa-bb,2*ab),largest=(aa+bb+disc)/2,smallest=Math.max(0,(aa+bb-disc)/2);observability=largest>1e-10?smallest/largest:0;rank=largest<=1e-10?0:observability<1e-4?1:2;const d=rank===2?ls(rows,b):[0,0];u+=d[0];v+=d[1];loss.push(e/rows.length);stages.push(stage('LK 迭代 '+(t+1),[heat('前帧',first),heat('对齐残差',grid((x,y)=>sample(x+u-p.dx,y+v-p.dy)-sample(x,y))),scatter('估计平移',[[0,0],[u,v]],[[0,0,u,v]])]));}return result([heat('前帧',first),heat('后帧',second),scatter('光流向量',[[u,v]],[[0,0,u,v]])],stages.length>1?stages:[stage('初始化',[heat('前帧',first),heat('后帧',second),scatter('初始流',[[0,0]])]),...stages],{'水平光流':u,'垂直光流':v,'位移误差':Math.hypot(u-p.dx,v-p.dy),'梯度矩阵秩':rank,'方向可观测比':observability},{u,v,truthU:p.dx,truthV:p.dy,loss,rank,observability,valid:rank===2},rank<2?'梯度矩阵秩不足，二维运动不可辨识；显示的零流是无效占位值，不代表估计成功。':input?'上传图像被实际采样并施加已知平移；误差对应人工变换真值。':'解析纹理施加已知亚像素平移，实际求解 LK 正规方程。');},'从亮度恒常和图像梯度估计亚像素运动。','迭代扭曲后求解 Σ∇I∇Iᵀ Δ=−Σ∇I r，更新全图共享平移。',['改变水平、垂直运动。','观察逐次残差。','上传纹理图并比较流估计。'],['孔径问题为何导致方程病态？','大运动为何需要图像金字塔？'],'仅估计全局平移；不能表示独立物体运动、遮挡和光照变化。'),
make('04','多视图结构与重投影优化','65–83',[c('baseline','相机间距',.2,1,.05,.5),c('noise','像素观测噪声',0,1,.05,.1),c('iterations','优化次数',2,20,1,8)],({params:p,seed})=>{const random=rng(seed),truth=Array.from({length:24},(_,i)=>[(i%6-2.5)*.2,(Math.floor(i/6)-1.5)*.2,2.5+(i%4)*.25]),cams=[-p.baseline,0,p.baseline],f=400,obs=truth.map(([x,y,z])=>cams.map(c=>[f*(x-c)/z+p.noise*(random()-.5),f*y/z+p.noise*(random()-.5)]));let pts=truth.map(q=>q.map((v,k)=>v+(random()-.5)*(k===2?1:.4))),initial=pts.map(q=>q.slice()),loss=[],stages=[];const objective=()=>pts.reduce((s,q,i)=>s+cams.reduce((ss,c,k)=>ss+(f*(q[0]-c)/q[2]-obs[i][k][0])**2+(f*q[1]/q[2]-obs[i][k][1])**2,0),0)/(truth.length*cams.length*2);loss.push(objective());for(let t=0;t<p.iterations;t++){pts=pts.map(([x,y,z],i)=>{let rows=[],b=[];cams.forEach((c,k)=>{rows.push([f/z,0,-f*(x-c)/(z*z)],[0,f/z,-f*y/(z*z)]);b.push(obs[i][k][0]-f*(x-c)/z,obs[i][k][1]-f*y/z);});const d=ls(rows,b);return [x+d[0],y+d[1],Math.max(.1,z+d[2])];});loss.push(objective());if(t===0||t===p.iterations-1)stages.push(stage('Gauss–Newton 第 '+(t+1)+' 次',[scatter('中心相机观测',obs.map(q=>q[1])),curves('重投影均方误差',loss.slice()),scatter('结构 X–Z',pts.map(q=>[q[0],q[2]]))]));}const e=Math.sqrt(pts.reduce((s,q,i)=>s+q.reduce((ss,v,k)=>ss+(v-truth[i][k])**2,0),0)/pts.length);return result([scatter('多相机观测',obs.flat()),curves('优化目标',loss),scatter('优化后 X–Z',pts.map(q=>[q[0],q[2]]))],stages,{'结构 RMSE':e,'最终像素 RMSE':Math.sqrt(loss.at(-1))},{loss,points:pts,initial,truth,structureError:e},'已知相机姿态的多视图结构优化；固定相机消除尺度规范自由度，未声称完整联合 bundle adjustment。');},'把多视图观测转换为结构，并通过重投影误差迭代优化。','已知三台相机，逐点求解投影雅可比的 Gauss–Newton 更新。',['观察带扰动的初始化。','增加观测噪声。','改变基线比较结构误差。'],['未知相机时尺度为何无法确定？','低重投影误差一定表示真实结构吗？'],'固定相机，仅优化三维点；不包括特征匹配、相机姿态优化及鲁棒外点处理。')];
scenes[2].supportsInput=true;
export const chapter={id:'005',title:'三维重建 II：几何、运动与多视图',sections:[
{id:'01',title:'相机模型与 Zhang 标定',pages:'3–23',relatedScene:'01',overview:'针孔相机通过内参、外参和透视除法产生图像；径向及切向畸变修正理想模型。Zhang 标定利用平面标靶的多姿态单应性约束初始化内参，再联合优化重投影误差。',conditions:'标靶尺寸与点对应可靠，多姿态应覆盖视场和倾角。实验固定主点与已知姿态，只拟合焦距和一阶径向畸变，不能替代完整 Zhang 标定。'},
{id:'02',title:'一般极线几何、RANSAC 与三角化',pages:'25–42',relatedScene:'02',overview:'一般未标定相机用基础矩阵 F 表示对应约束 x₂ᵀFx₁=0，已知内参时可转为本质矩阵。归一化八点法要求足够非退化对应并施加秩二约束；RANSAC 用最小样本与残差筛选外点，再在内点上重估。',conditions:'平面或低视差场景可能退化；极线约束不能单独保证匹配唯一。实验展示已知平行双目的 F 与视差三角化，未运行一般 F 估计或 RANSAC。'},
{id:'03',title:'运动估计与 Lucas–Kanade',pages:'44–63',relatedScene:'03',overview:'亮度恒常与局部小运动将光流线性化；Lucas–Kanade 用窗口内多个梯度约束求解运动，迭代扭曲改善亚像素对齐，金字塔用于较大位移。',conditions:'纹理梯度必须覆盖两个方向；遮挡、亮度变化和孔径问题使估计不可靠。实验估计全局平移，上传图像会实际参与采样和人工位移生成。'},
{id:'04',title:'多视图结构、SfM 与 Bundle Adjustment',pages:'65–83',relatedScene:'04',overview:'SfM 结合特征跟踪、相对姿态与三角化初始化相机和结构。Bundle Adjustment 联合优化相机参数与三维点的重投影误差，通常加入鲁棒损失，并固定坐标和尺度规范自由度。',conditions:'需要可靠对应、足够基线和合理初始化；纯旋转无法恢复深度。实验固定三个相机，实际迭代优化三维点，不声称执行联合相机与结构 BA。'}]};


