import {sigmoid,rng,dot,mlpForward,mlpLoss,mlpGradient,curve,bars,matrix,scatter,control,result,scene,trainLinear,accuracy} from './learning-math.mjs';
export const chapter={id:'007',title:'机器学习：从数据到可训练网络',sections:[{title:'任务、数据划分与泛化',pages:'3–17',relatedScene:'01',overview:'监督、无监督、分类与回归；先按来源划分，再拟合预处理。适用于有明确任务与评价数据的情境。'},{title:'优化与损失',pages:'19–35',relatedScene:'02',overview:'经验风险、梯度下降、学习率与收敛；可微目标允许梯度优化，非凸优化不保证全局最优。'},{title:'经典分类器',pages:'37–53',relatedScene:'03',overview:'KNN、线性分类、支持向量机与间隔；距离需要合理尺度，线性模型依赖可分特征。'},{title:'多层感知机与反向传播',pages:'55–84',relatedScene:'04',overview:'非线性激活、链式法则、梯度校验；足够隐藏单元可学习非线性关系。'},{title:'卷积神经网络',pages:'86–104',relatedScene:'05',overview:'局部连接、参数共享、卷积、池化与分类；适用于局部空间结构，平移并非总能完全不变。'}]};
const samples=seed=>{let r=rng(seed);return Array.from({length:80},()=>{let x=r()*2-1,y=r()*2-1;return [[x,y,1],+(x+y>0)]})};
export const scenes=[
scene('01','数据划分与泄漏','3–17','比较独立测试与重复训练样本造成的乐观评价。','训练逻辑回归后，用真实预测计算训练、独立测试、泄漏混合测试的准确率。',[control('leak','泄漏比例',0,1,.1,.5)],({params,seed})=>{let train=samples(seed).slice(0,24),test=samples(seed+91).slice(0,24),fit=trainLinear(train,150,.15),n=Math.round(params.leak*24),mixed=[...train.slice(0,n),...test.slice(n)],predict=x=>+(sigmoid(dot(fit.w,x))>=.5),values=[accuracy(train,predict),accuracy(test,predict),accuracy(mixed,predict)];return result([scatter('训练合成样本',train.map(([x,y])=>[x[0],x[1],y])),curve('训练交叉熵',fit.losses),bars('实际准确率',values,['训练24','独立测试24','泄漏测试24'])],{...fit,accuracy:values,trainCount:24,testCount:24,leakedCount:n},[{label:'独立测试准确率',value:values[1]}],'泄漏测试包含训练样本；偶然不升高并不代表泄漏安全。',[scatter('独立测试样本',test.map(([x,y])=>[x[0],x[1],y])),curve('初期损失',fit.losses.slice(0,10)),bars('初始权重',[0,0,0])])}),
scene('02','损失与梯度下降','19–35','观察真实迭代如何最小化二次损失。','对 L=(w−3)² 求导 2(w−3)，按 w←w−η∇L 更新。',[control('rate','学习率',.01,.9,.01,.15),control('steps','迭代次数',5,100,1,30)],({params})=>{let w=-2,weights=[],losses=[],gradients=[];for(let i=0;i<=params.steps;i++){weights.push(w);losses.push((w-3)**2);gradients.push(2*(w-3));if(i<params.steps)w-=params.rate*gradients.at(-1)}return result([curve('参数轨迹',weights),curve('损失轨迹',losses),bars('最终参数和梯度',[w,gradients.at(-1)])],{weights,losses,gradients},[{label:'最终损失',value:losses.at(-1)}],'所有点来自实际迭代；学习率接近1时会振荡。',[curve('初期参数',weights.slice(0,3)),curve('初期损失',losses.slice(0,3)),bars('初始梯度',[gradients[0]])])}),
scene('03','KNN、线性分类与间隔','37–53','在相同训练和测试划分比较三种分类机制。','KNN投票；逻辑回归优化交叉熵；线性SVM优化hinge损失。',[control('k','邻居数量',1,15,2,5)],({params,seed})=>{let train=samples(seed).slice(0,50),test=samples(seed+13).slice(0,30),log=trainLinear(train),svm=trainLinear(train,120,.1,true),knn=x=>{let nn=train.map(([z,y])=>[z.reduce((s,v,j)=>s+(v-x[j])**2,0),y]).sort((a,b)=>a[0]-b[0]).slice(0,params.k);return +(nn.reduce((s,z)=>s+z[1],0)>=nn.length/2)},values=[accuracy(test,knn),accuracy(test,x=>+(dot(log.w,x)>=0)),accuracy(test,x=>+(dot(svm.w,x)>=0))];return result([scatter('训练样本50',train.map(([x,y])=>[x[0],x[1],y])),{kind:'curves',title:'训练目标',series:[{label:'交叉熵',points:log.losses.map((v,i)=>[i,v])},{label:'hinge + L2（λ=0.05）',points:svm.losses.map((v,i)=>[i,v])}]},bars('独立合成测试30准确率',values,['KNN','逻辑回归','SVM'])],{log,svm,lambda:.05,regularizedBias:false,accuracy:values,k:params.k},[{label:'KNN测试准确率',value:values[0]}],'hinge与交叉熵的数值尺度不同，不能以损失大小直接判断模型优劣。',[scatter('测试样本',test.map(([x,y])=>[x[0],x[1],y])),curve('初期hinge',svm.losses.slice(0,5)),bars('零权重',[0,0,0])])}),
scene('04','MLP反向传播学习XOR','55–84','用解析梯度训练三隐藏单元网络解决XOR。','逐层计算 sigmoid；交叉熵的输出梯度为p−y；隐藏层使用链式法则。',[control('steps','训练轮数',100,4000,100,2500),control('rate','学习率',.05,1,.05,.8)],({params,seed})=>{let r=rng(seed),w=Array.from({length:13},()=>r()*2-1),data=[[[0,0],0],[[0,1],1],[[1,0],1],[[1,1],0]],initial=w.slice(),losses=[];for(let t=0;t<=params.steps;t++){losses.push(data.reduce((s,[x,y])=>s+mlpLoss(w,x,y),0)/4);if(t<params.steps){let g=Array(13).fill(0);for(let [x,y]of data)mlpGradient(w,x,y).forEach((v,j)=>g[j]+=v/4);w=w.map((v,j)=>v-params.rate*g[j])}}let predictions=data.map(([x])=>mlpForward(w,x).p),acc=data.reduce((s,[,y],i)=>s+(+(predictions[i]>=.5)===y),0)/4;return result([matrix('XOR真值',[[0,1],[1,0]]),curve('真实交叉熵',losses),matrix('预测概率',[predictions.slice(0,2),predictions.slice(2)])],{weights:w,initial,losses,predictions,accuracy:acc},[{label:'四个训练样本准确率',value:acc}],'这是四个合成训练样本，不代表独立测试泛化。',[matrix('XOR真值',[[0,1],[1,0]]),curve('前10轮损失',losses.slice(0,11)),matrix('初始概率',data.map(([x])=>[mlpForward(initial,x).p]))])}),
scene('05','可训练微型CNN','86–104','同时优化卷积滤波器与分类层区分横线和竖线。','4×4图像→两个2×2卷积→ReLU→全局平均池化→sigmoid；梯度回传到卷积核。',[control('steps','训练轮数',50,600,25,300),control('rate','学习率',.02,.5,.02,.2)],({params,seed})=>{let r=rng(seed),data=Array.from({length:24},(_,i)=>{let y=i%2,pos=Math.floor(i/2)%4,img=Array.from({length:16},(_,j)=>Math.min(1,(y?j%4===pos:Math.floor(j/4)===pos)? .85+r()*.15:r()*.08));return [img,y]}),filters=Array.from({length:2},()=>Array.from({length:4},()=>r()*.6-.1)),initial=filters.map(x=>x.slice()),head=[.2,-.2,0],losses=[];const forward=img=>{let maps=filters.map(f=>Array.from({length:9},(_,j)=>{let row=Math.floor(j/3),col=j%3;return dot(f,[img[row*4+col],img[row*4+col+1],img[(row+1)*4+col],img[(row+1)*4+col+1]])})),pool=maps.map(m=>m.reduce((s,v)=>s+Math.max(0,v),0)/9);return {maps,pool,p:sigmoid(dot(head,[...pool,1]))}};for(let t=0;t<=params.steps;t++){let fg=filters.map(()=>[0,0,0,0]),hg=[0,0,0],loss=0;for(let [img,y]of data){let {maps,pool,p}=forward(img),d=(p-y)/data.length;loss+=-y*Math.log(p+1e-12)-(1-y)*Math.log(1-p+1e-12);hg[0]+=d*pool[0];hg[1]+=d*pool[1];hg[2]+=d;maps.forEach((m,k)=>m.forEach((v,j)=>{if(v>0){let row=Math.floor(j/3),col=j%3,patch=[img[row*4+col],img[row*4+col+1],img[(row+1)*4+col],img[(row+1)*4+col+1]];patch.forEach((z,l)=>fg[k][l]+=d*head[k]*z/9)}}))}losses.push(loss/data.length);if(t<params.steps){filters=filters.map((f,k)=>f.map((v,j)=>v-params.rate*fg[k][j]));head=head.map((v,j)=>v-params.rate*hg[j])}}let prediction=data.map(([x])=>forward(x).p),acc=data.reduce((s,[,y],i)=>s+(+(prediction[i]>.5)===y),0)/data.length;return result([matrix('合成横线输入',Array.from({length:4},(_,i)=>data[0][0].slice(i*4,i*4+4))),matrix('训练后的两个卷积核',filters),curve('CNN训练损失',losses)],{filters,initialFilters:initial,head,losses,prediction,accuracy:acc,pooling:forward(data[0][0]).pool},[{label:'合成训练24准确率',value:acc}],'卷积核与分类层均参与真实训练；没有真实图片或预训练权重。',[matrix('同一输入',Array.from({length:4},(_,i)=>data[0][0].slice(i*4,i*4+4))),matrix('初始卷积核',initial),curve('前10轮损失',losses.slice(0,11))])})];
const teaching=[
{steps:['查看24个训练样本与另外24个独立测试样本。','提高泄漏比例，真实训练逻辑回归后混入指定数量的训练样本。','比较三个准确率和独立测试误差，记录泄漏数量。'],questions:['为什么泄漏测试包含训练样本后不再是独立评价？','这一次泄漏准确率没有提高是否说明数据划分正确？'],failure:'泄漏比例越高，测试独立性越差；24个样本的随机波动可能掩盖乐观偏差。'},
{steps:['从w=−2开始，检查目标w=3与初始梯度。','调整学习率和迭代次数，执行每一步梯度下降。','比较参数振荡、梯度幅度与最终二次损失。'],questions:['学习率大于0.5时为什么参数会越过最优点？','增加迭代次数何时无法弥补不合适的学习率？'],failure:'学习率接近上限0.9会造成明显振荡；轮数太少时参数仍远离最优点。'},
{steps:['固定50个训练样本与30个独立合成测试样本。','改变K并训练交叉熵线性分类器与L2正则hinge分类器。','比较真实测试准确率与两种目标的下降曲线。'],questions:['K过小与过大分别怎样影响局部边界？','为何hinge加L2的目标值不能与交叉熵直接比较？'],failure:'K=1容易受邻居噪声影响，K过大可能抹平边界；线性模型无法表达弯曲决策边界。'},
{steps:['查看XOR真值与随机初始化的预测概率。','设置学习率和训练轮数，运行三隐藏单元的解析反向传播。','比较四个概率、交叉熵下降和训练样本准确率。'],questions:['去掉隐藏层非线性后为什么不能表示XOR？','解析梯度与有限差分一致能证明训练一定收敛吗？'],failure:'轮数仅100或学习率过小可能未学会XOR；四个训练样本的准确率不等于泛化准确率。'},
{steps:['查看4×4合成线条和两个随机2×2卷积核。','训练卷积核、全局平均池化后的分类层，并保存真实损失。','比较初始与最终核数值以及24个训练样本预测。'],questions:['参数共享怎样减少卷积核的可训练参数数量？','如果只更新分类头，能否称为训练卷积特征？'],failure:'训练轮数过少可能导致特征未分离；全局池化丢失位置，不能保证识别复杂真实图像。'}];
scenes.forEach((s,i)=>Object.assign(s,teaching[i]));
chapter.sections[0].overview+=' 泛化、过拟合及正则化需要结合独立验证集判断。';
chapter.sections[1].overview+=' L2正则化限制权重规模，验证集用于选择强度，测试集用于最后报告。';
scenes[2].principle='KNN投票；逻辑回归优化交叉熵；线性SVM优化平均hinge + λ‖w‖²/2（λ=0.05，偏置不正则化）。';

