import {N,grid,heat,curves,rmse,ls,rng,control as c,scene,result,stage,clamp,sfsObjectiveGradient} from './geometry-numeric.mjs';
const file='004-三维重建1.pptx';
const make=(id,title,pages,controls,compute,goal,principle,steps,questions,failure)=>scene(id,title,pages,controls,compute,goal,principle,steps,questions,failure,file);
export const scenes=[
make('01','BRDF 与图像形成','3–22',[c('roughness','高光粗糙度',0.08,1,0.02,.4),c('angle','光源角度',0,75,1,30),c('exposure','相对曝光时间',.25,2,.05,1),c('fnumber','光圈 F 数',1.4,8,.2,2.8)],({params:p})=>{const a=p.angle*Math.PI/180,L=[Math.sin(a),0,Math.cos(a)],normal=grid((x,y)=>{const u=(x-15.5)/20,v=(y-15.5)/20;const n=[u,v,Math.sqrt(Math.max(.01,1-u*u-v*v))],l=Math.hypot(...n);return n.map(v=>v/l);}),diff=normal.map(n=>Math.max(0,n.reduce((s,v,i)=>s+v*L[i],0))),spec=normal.map(n=>{const h=[L[0],0,L[2]+1],l=Math.hypot(...h);return Math.pow(Math.max(0,n.reduce((s,v,i)=>s+v*h[i]/l,0)),2/(p.roughness*p.roughness));}),img=diff.map((v,i)=>(.65*v+.35*spec[i])*p.exposure*(2.8/p.fnumber)**2),views=[heat('法线 z 分量',normal.map(n=>n[2])),heat('漫反射',diff),heat('漫反射 + 高光',img)];return result(views,[stage('Lambert 漫反射',views),stage('加入半角向量高光',[views[0],heat('高光分量',spec),views[2]])],{'平均亮度':img.reduce((a,b)=>a+b)/img.length,'高光峰值':Math.max(...spec)},{diffuse:diff,specular:spec,intensity:img,normalNorms:normal.map(n=>Math.hypot(...n)),exposureScale:p.exposure*(2.8/p.fnumber)**2});},'区分几何、材质和光照对亮度的贡献。','Lambert 项为 max(n·L,0)；Blinn 高光使用半角向量，粗糙度控制指数；线性传感器曝光强度正比于曝光时间、反比于 F 数平方。',['旋转光源观察阴影边界。','改变粗糙度比较高光面积。','比较两种反射分量。'],['亮度能唯一确定法线吗？','为何高光会破坏 Lambert 假设？'],'未建模互反射、遮挡和能量归一化；这是局部反射机制实验。'),
make('02','光度立体与表面积分','24–45',[c('noise','强度噪声',0,.12,.005,.005),c('iterations','积分迭代',20,300,10,160),c('light','查看光照编号',1,4,1,1)],({params:p,seed})=>{const random=rng(seed),z=grid((x,y)=>.8*Math.sin(x/10)*Math.cos(y/12)),norm=grid((x,y)=>{const dx=.08*Math.cos(x/10)*Math.cos(y/12),dy=-.8/12*Math.sin(x/10)*Math.sin(y/12),l=Math.hypot(dx,dy,1);return [-dx/l,-dy/l,1/l];}),L=[[.5,0,.866],[-.5,0,.866],[0,.5,.866],[0,-.5,.866]],images=L.map(l=>norm.map(n=>.8*n.reduce((s,v,k)=>s+v*l[k],0)+p.noise*(random()-.5))),est=norm.map((_,i)=>{const g=ls(L,images.map(a=>a[i])),d=Math.hypot(...g);return g.map(v=>v/d);}),gx=est.map(n=>-n[0]/n[2]),gy=est.map(n=>-n[1]/n[2]);let h=Array(N*N).fill(0),snap=[];for(let t=0;t<p.iterations;t++){const q=h.slice();for(let y=0;y<N;y++)for(let x=0;x<N;x++){const i=y*N+x;let sum=0,k=0;if(x>0){sum+=h[i-1]+gx[i-1];k++;}if(x<N-1){sum+=h[i+1]-gx[i];k++;}if(y>0){sum+=h[i-N]+gy[i-N];k++;}if(y<N-1){sum+=h[i+N]-gy[i];k++;}q[i]=sum/k;}const anchor=q[0];h=q.map(v=>v-anchor);if(t===0||t===Math.floor(p.iterations/2)||t===p.iterations-1)snap.push(stage('Poisson/Jacobi 第 '+(t+1)+' 次',[heat('光照 '+p.light,images[Math.round(p.light)-1]),heat('法线 z',est.map(n=>n[2])),heat('积分高度',h,'surface')]));}const e=Math.sqrt(est.reduce((s,n,i)=>s+n.reduce((r,v,k)=>r+(v-norm[i][k])**2,0),0)/est.length);return result([heat('光照 '+p.light,images[Math.round(p.light)-1]),heat('法线 z',est.map(n=>n[2])),heat('积分表面',h,'surface')],snap,{'法线向量 RMSE':e,'高度 RMSE':rmse(h,z.map(v=>v-z[0]))},{normalError:e,height:h,truth:z,normals:est,images,selectedLight:p.light});},'从多光照估计法线，并理解梯度积分的边界条件。','每像素求解 I=L(ρn) 的最小二乘，再用离散梯度约束迭代积分。',['比较四张光照强度。','增大噪声观察法线误差。','增加迭代次数观察积分收敛。'],['为何至少需要三个独立光源？','高度常数为什么无法恢复？'],'阴影、镜面、未知光源和近共线光源使最小二乘失效；积分固定左上角高度。'),
make('03','单图像 SFS 的迭代与歧义','47–66',[c('regularization','平滑权重',0,2,.05,.2),c('iterations','梯度迭代',10,240,10,100),c('initial','初始坡度符号',-1,1,2,1)],({params:p})=>{const truth=grid((x,y)=>.18+.13*Math.sin(x/5)*Math.cos(y/7)),I=truth.map(v=>1/Math.sqrt(1+v*v));let q=Array(N*N).fill(p.initial*.55),loss=[],stages=[];for(let t=0;t<p.iterations;t++){const current=sfsObjectiveGradient(q,I,N,p.regularization);q=q.map((v,i)=>v-(.35/(1+p.regularization))*q.length*current.gradient[i]);loss.push(sfsObjectiveGradient(q,I,N,p.regularization).objective);if(t===0||t===Math.floor(p.iterations/2)||t===p.iterations-1)stages.push(stage('亮度约束迭代 '+(t+1),[heat('单光照强度',I),curves('优化目标',loss.slice()),heat('估计坡度',q)]));}const pred=q.map(v=>1/Math.sqrt(1+v*v));return result([heat('观测强度',I),curves('迭代目标',loss),heat('坡度场',q)],stages,{'强度 RMSE':rmse(pred,I),'坡度 RMSE':rmse(q,truth)},{loss,slope:q,truth,oppositeIntensity:q.map(v=>1/Math.sqrt(1+(-v)**2))},'一维坡度场的 SFS 机制：单幅正面光照无法区分坡度正负；不声称恢复一般三维形状。');},'通过优化理解亮度约束、正则项和凹凸歧义。','最小化 Lambert 亮度残差与邻域平滑项；I(p)=I(−p) 产生双解。',['观察实际迭代损失。','改变平滑权重。','切换初始符号比较解。'],['低亮度残差为何不保证正确形状？','正则化引入什么先验？'],'仅优化一维局部坡度，不满足一般二维表面的完整可积性；正面光源存在符号歧义。'),
make('04','焦点堆栈 DFF','68–85',[c('aperture','离焦强度',.3,2,.1,1),c('noise','传感器噪声',0,.08,.005,.005)],({params:p,seed})=>{const random=rng(seed),truth=grid(x=>x<11?0:x<22?2:4),stack=Array.from({length:5},(_,k)=>grid((x,y)=>.5+.32*Math.exp(-p.aperture*Math.abs(k-truth[y*N+x]))*Math.cos(x*1.6)*Math.cos(y*1.3)+p.noise*(random()-.5))),energy=stack.map(a=>grid((x,y)=>{let e=0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const xx=clamp(x+dx,1,N-2),yy=clamp(y+dy,1,N-2),i=yy*N+xx;e+=Math.abs(a[i-1]+a[i+1]+a[i-N]+a[i+N]-4*a[i]);}return e;})),depth=truth.map((_,i)=>energy.reduce((best,a,k)=>a[i]>energy[best][i]?k:best,0)),confidence=truth.map((_,i)=>{const sorted=energy.map(a=>a[i]).sort((a,b)=>b-a);return (sorted[0]-sorted[1])/Math.max(1e-12,sorted[0]);}),valid=confidence.map(v=>v>.15),accuracy=depth.filter((v,i)=>v===truth[i]).length/depth.length,views=[heat('焦平面 0',stack[0]),heat('焦平面 2 清晰度',energy[2]),heat('最大清晰度深度',depth)];return result(views,[stage('第一个焦平面',[heat('焦平面 0',stack[0]),heat('清晰度 0',energy[0]),heat('已知深度',truth)]),stage('全堆栈选择最大值',views)],{'深度准确率':accuracy,'层级 RMSE':rmse(depth,truth),'有效像素比例':valid.filter(Boolean).length/valid.length,'平均置信度':confidence.reduce((s,v)=>s+v,0)/confidence.length},{accuracy,depth,truth,focusEnergy:energy,stack,confidence,valid},'合成纹理由离焦调制对比度；不是完整薄透镜散焦 PSF 仿真。');},'用局部清晰度在焦点堆栈中估计深度。','计算窗口内绝对离散 Laplacian，选择焦平面响应的最大值。',['比较近、中、远焦平面。','改变离焦强度和噪声。','检查深度分界处误差及有效像素比例；数值导出含最佳/次佳响应置信度与掩膜。'],['无纹理区域为什么不可靠？','焦点层级如何换算物理距离？'],'使用对比度衰减的合成离焦模型；边界窗口混合与噪声会造成深度误判。'),
make('05','Gray 编码与四步相移','87–108',[c('noise','投影强度噪声',0,.15,.005,.01),c('period','相位条纹周期',4,16,1,8)],({params:p,seed})=>{const random=rng(seed),coord=grid((x,y)=>x+.25+.15*Math.sin(y/4)),gray=Array.from({length:5},(_,bit)=>coord.map(u=>{const k=Math.floor(u),g=k^(k>>1);return (g>>(4-bit))&1;})),phase=Array.from({length:4},(_,k)=>coord.map(u=>.5+.4*Math.cos(2*Math.PI*u/p.period+k*Math.PI/2)+p.noise*(random()-.5))),wrapped=coord.map((_,i)=>{let a=Math.atan2(phase[3][i]-phase[1][i],phase[0][i]-phase[2][i]);return (a+2*Math.PI)%(2*Math.PI)*p.period/(2*Math.PI);}),decoded=coord.map((_,i)=>{let g=gray.reduce((v,b)=>(v<<1)|b[i],0),b=g;for(let shift=1;shift<32;shift*=2)b^=b>>shift;const w=wrapped[i];return w+Math.round((b+.5-w)/p.period)*p.period;}),e=rmse(decoded,coord),views=[heat('Gray 最高位',gray[0]),heat('包裹相位坐标',wrapped),heat('解包裹投影坐标',decoded)];return result(views,[stage('二值 Gray 解码',[views[0],heat('四步条纹之一',phase[0]),heat('整数坐标',coord.map(Math.floor))]),stage('相位解包裹',views)],{'投影坐标 RMSE（像素）':e},{rmse:e,coordinate:decoded,truth:coord,gray,phase});},'把 Gray 的绝对编码与相移的亚像素精度结合。','五位 Gray 提供整数位置；atan2(I₃−I₁,I₀−I₂) 得到包裹相位，按整数编码选择周期。',['观察二值编码。','调整周期查看相位跳变。','增加噪声观察坐标误差。'],['Gray 相邻码为何只差一位？','遮挡导致无效编码应如何检测？'],'假设编码位无噪声且同步准确；演示输出投影坐标，未假设未知相机/投影仪标定来伪造深度。')];
export const chapter={id:'004',title:'三维重建 I：光照、焦点与主动测量',sections:[
{id:'01',title:'反射与成像',pages:'3–22',relatedScene:'01',overview:'从表面 BRDF、光照方向到传感器辐照度，再到曝光与数字图像。光圈改变通光量，也改变景深和衍射；本实验只计算线性曝光缩放。',conditions:'局部反射、固定光源、线性响应；饱和、色调映射、镜头渐晕和完整辐射标定不在模拟内。'},
{id:'02',title:'光度立体、光源标定与 GBR',pages:'24–45',relatedScene:'02',overview:'已标定光度立体通过多光源恢复法线与反照率。未知光源时，矩阵分解存在广义浅浮雕 GBR 歧义，需光源标定、几何或材质先验。稳健光度立体通过有效光照选择、鲁棒损失或低秩/稀疏分解处理阴影与高光。',conditions:'光源方向必须充分独立；普通最小二乘需要近 Lambert 反射。积分还需要可积性和边界约束。实验采用已知四光源，不宣称消除 GBR。'},
{id:'03',title:'SFS 与形状歧义',pages:'47–66',relatedScene:'03',overview:'单图像恢复形状需要反射模型、光照和边界先验；亮度约束不足以唯一确定法线，凹凸、光照与反照率可以相互补偿。',conditions:'本实验在正面光源下优化一维坡度，展示真实迭代和正负歧义；一般二维 SFS 还需要完整可积性约束。'},
{id:'04',title:'聚焦、散焦与 PSF/MTF',pages:'68–85',relatedScene:'04',overview:'DFF 从焦点堆栈的清晰度峰值选择深度；DFD 利用散焦尺度推断距离。PSF 描述点扩散，MTF 是光学传递函数幅值，用来量化空间频率衰减。',conditions:'纹理、对齐、曝光一致性与镜头标定决定可靠性。实验用对比度衰减演示清晰度选择，并导出最佳/次佳响应置信度与有效掩膜，不把它当作完整薄透镜 PSF 仿真。'},
{id:'05',title:'结构光与 ToF 主动深度',pages:'87–108',relatedScene:'05',overview:'结构光用 Gray 编码获取绝对对应，四步相移提供亚像素位置；标定相机与投影仪后可三角化。ToF 则由飞行时间 d=cΔt/2 或调制相位估计距离，周期相位会带来距离歧义。',conditions:'结构光要求同步、可见投影与几何标定；ToF 受多径、环境光和反射率影响。当前数值实验输出投影坐标，没有模拟 ToF 硬件或伪造物理深度。'}]};




