import {sigmoid,rng,dot,mse,attention,iou,curve,bars,matrix,scatter,control,result,scene} from './learning-math.mjs';
export const chapter={id:'008',title:'深度学习机制：轻量真实计算',sections:[{title:'迁移学习',pages:'3–20',relatedScene:'01',overview:'预训练、冻结特征与微调；源域与目标域相关时可能有效，负迁移仍可能发生。'},{title:'检测与分割',pages:'22–59',relatedScene:'02',overview:'框回归、IoU、NMS、语义与实例分割、掩码指标；目标和阈值需明确。本实验不运行检测大模型。'},{title:'注意力与视觉Transformer',pages:'81–118',relatedScene:'03',overview:'Q/K/V、softmax、patch嵌入、位置编码、多头注意力；序列长度增大会增加二次计算成本。仅计算小矩阵机制。'},{title:'自编码器与扩散',pages:'138–175',relatedScene:'04',overview:'瓶颈重建、变分建模、加噪与去噪；实际训练小型AE及一维噪声预测器，不代表大型图像生成。'},{title:'图文对齐与视觉语言模型',pages:'177–213',relatedScene:'05',overview:'对比学习、余弦检索、零样本分类、CLIP与VLM概念；配对数据决定对齐效果。本实验仅优化玩具特征嵌入，无语言理解能力。'}]};
const make=(id,title,pages,goal,principle,controls,fn)=>scene(id,title,pages,goal,principle,controls,fn,'008');
export const scenes=[
make('01','真实预训练与冻结迁移','3–20','比较冻结隐藏层与微调整个小网络的目标域损失。','先在源域优化1→3→1网络，再复制参数到目标域分别训练分类头和全网络。',[control('steps','每阶段轮数',50,500,25,250),control('shift','目标域平移',0,1,.1,.5)],({params,seed})=>{let r=rng(seed),initial=Array.from({length:10},()=>r()*2-1),source=Array.from({length:40},(_,i)=>[(i-20)/10,+(i>=20)]),target=source.map(([x])=>[x,+(x>params.shift)]);function train(w,data,frozen){let losses=[];for(let t=0;t<=params.steps;t++){let g=Array(10).fill(0),loss=0;for(let [x,y]of data){let h=[0,1,2].map(j=>Math.tanh(w[j*2]*x+w[j*2+1])),p=sigmoid(dot(h,w.slice(6,9))+w[9]),d=(p-y)/data.length;loss+=-y*Math.log(p+1e-12)-(1-y)*Math.log(1-p+1e-12);h.forEach((v,j)=>{g[6+j]+=d*v;if(!frozen){g[2*j]+=d*w[6+j]*(1-v*v)*x;g[2*j+1]+=d*w[6+j]*(1-v*v)}});g[9]+=d}losses.push(loss/data.length);if(t<params.steps)w=w.map((v,j)=>v-.2*g[j])}return {w,losses}}let pre=train(initial.slice(),source,false),frozen=train(pre.w.slice(),target,true),adapted=train(pre.w.slice(),target,false);return result([scatter('源域与目标标签',target.map(([x,y])=>[x,y,y])),curve('源域真实预训练损失',pre.losses),{kind:'curves',title:'目标域优化损失',series:[{label:'冻结',points:frozen.losses.map((v,i)=>[i,v])},{label:'微调',points:adapted.losses.map((v,i)=>[i,v])}]}],{initial,pretrained:pre.w,frozen:frozen.w,adapted:adapted.w,losses:pre.losses,frozenLosses:frozen.losses,adaptedLosses:adapted.losses},[{label:'微调最终损失',value:adapted.losses.at(-1)}],'均为40个合成训练样本；未声称独立测试准确率。',[bars('初始参数',initial),curve('前5轮预训练',pre.losses.slice(0,6)),bars('预训练隐藏层',pre.w.slice(0,6))])}),
make('02','框、NMS与分割指标','22–59','实际计算重叠框抑制及掩码IoU/Dice。','NMS按分数排序并抑制IoU超过阈值的框；像素交并集计算分割指标。',[control('threshold','NMS IoU阈值',.1,.9,.1,.5),control('offset','预测掩码位移',0,3,1,1)],({params})=>{let boxes=[[1,1,5,5],[2,1,6,5],[5,5,8,8]],scores=[.9,.8,.7],kept=[];for(let i of [0,1,2])if(kept.every(j=>iou(boxes[i],boxes[j])<=params.threshold))kept.push(i);let truth=Array.from({length:64},(_,i)=>+(i%8>=2&&i%8<6&&Math.floor(i/8)>=2&&Math.floor(i/8)<6)),pred=Array.from({length:64},(_,i)=>+(i%8>=2+params.offset&&i%8<6+params.offset&&Math.floor(i/8)>=2&&Math.floor(i/8)<6)),intersection=truth.reduce((s,v,i)=>s+v*pred[i],0),sum=truth.reduce((s,v)=>s+v,0)+pred.reduce((s,v)=>s+v,0),miou=intersection/(sum-intersection),dice=2*intersection/sum;return result([{kind:'scatter',title:'NMS保留框',points:kept.map(i=>[boxes[i][0],boxes[i][1],i]),lines:kept.flatMap(i=>{let [a,b,c,d]=boxes[i];return [[a,b,c,b],[c,b,c,d],[c,d,a,d],[a,d,a,b]]}),domain:[0,8,0,8]},matrix('真值掩码',Array.from({length:8},(_,i)=>truth.slice(i*8,i*8+8))),matrix('位移预测掩码',Array.from({length:8},(_,i)=>pred.slice(i*8,i*8+8)))],{boxes,scores,kept,boxIoU:iou(boxes[0],boxes[1]),intersection,maskIoU:miou,dice,truth,pred},[{label:'掩码IoU',value:miou},{label:'Dice',value:dice}],'框和掩码均为合成几何输入，没有运行检测/分割网络。',[bars('候选框分数',scores),bars('逐对IoU',[iou(boxes[0],boxes[1]),iou(boxes[0],boxes[2])]),bars('抑制后分数',kept.map(i=>scores[i]))])}),
make('03','QKV注意力与patch token','81–118','验证缩放点积、softmax归一化及patch维度。','4×4图像拆为四个2×2 patch；固定投影得到4×2 Q/K/V并计算softmax(QKᵀ/√2)V。',[control('scale','QK投影尺度',.2,3,.2,1)],({params})=>{let image=[[1,1,0,0],[1,1,0,0],[0,0,.5,.5],[0,0,.5,.5]],patches=[[1,1,1,1],[0,0,0,0],[0,0,0,0],[.5,.5,.5,.5]],q=patches.map((p,i)=>[(p[0]+p[3])*params.scale,i*.2]),k=patches.map((p,i)=>[(p[1]+p[2])*params.scale,i*.2]),v=patches.map((p,i)=>[p.reduce((a,b)=>a+b)/4,i/3]),a=attention(q,k,v);return result([matrix('4×4合成图像',image),matrix('4×4注意力权重',a.weights),matrix('4×2输出tokens',a.output)],{image,patches,q,k,v,...a,dimensions:{patchCount:4,patchFeatures:4,embedding:2,attentionRows:4}},[{label:'第一行权重和',value:a.weights[0].reduce((s,v)=>s+v,0)}],'固定投影演示精确注意力运算；没有训练ViT，不包含大型模型推理。',[matrix('patch矩阵4×4',patches),matrix('softmax前scores',a.scores),matrix('原始V',v)])}),
make('04','玩具AE与一维扩散训练','138–175','真实训练瓶颈AE和噪声预测器，然后运行反向采样。','AE:2→1→2线性瓶颈；扩散前向xₜ=√ᾱx₀+√(1−ᾱ)ε，三次多项式时间特征预测ε，DDIM式反向更新。',[control('steps','训练轮数',100,1500,100,700),control('noise','初始采样噪声',-2,2,.1,1)],({params,seed})=>{let r=rng(seed),points=Array.from({length:40},(_,i)=>{let x=(i-20)/10;return [x,.7*x]}),w=[.3,.2,.2,.3],initial=w.slice(),aeLosses=[];for(let t=0;t<=params.steps;t++){let g=[0,0,0,0],loss=0;for(let x of points){let z=w[0]*x[0]+w[1]*x[1],e=[w[2]*z-x[0],w[3]*z-x[1]];loss+=dot(e,e)/2;g[2]+=e[0]*z/40;g[3]+=e[1]*z/40;let dz=e[0]*w[2]+e[1]*w[3];g[0]+=dz*x[0]/40;g[1]+=dz*x[1]/40}aeLosses.push(loss/40);if(t<params.steps)w=w.map((v,j)=>v-.05*g[j])}const normal=()=>Math.sqrt(-2*Math.log(Math.max(1e-9,r())))*Math.cos(2*Math.PI*r());const feat=(x,t)=>[1,x,x*x/4,x*x*x/8,t,x*t];let training=Array.from({length:240},()=>{let t=.1+r()*.85,x0=normal()*.5+.8,a=Math.exp(-3*t),eps=normal(),xt=Math.sqrt(a)*x0+Math.sqrt(1-a)*eps;return [feat(xt,t),eps]}),theta=Array(6).fill(0),diffusionLosses=[];for(let i=0;i<=params.steps;i++){let g=Array(6).fill(0),loss=0;for(let [f,y]of training){let e=dot(theta,f)-y;loss+=e*e;f.forEach((v,j)=>g[j]+=2*e*v/training.length)}diffusionLosses.push(loss/training.length);if(i<params.steps)theta=theta.map((v,j)=>v-.01*g[j])}let x=params.noise,trajectory=[x],predictedNoise=[];for(let i=20;i>=1;i--){let t=i/20,a=Math.exp(-3*t),ap=Math.exp(-3*(i-1)/20),e=dot(theta,feat(x,t));predictedNoise.push(e);let x0=(x-Math.sqrt(1-a)*e)/Math.sqrt(a);x=Math.sqrt(ap)*x0+Math.sqrt(1-ap)*e;trajectory.push(x)}let reconstructed=points.map(p=>{let z=w[0]*p[0]+w[1]*p[1];return [w[2]*z,w[3]*z]});return result([scatter('AE合成输入',points),{kind:'curves',title:'实际训练损失',series:[{label:'AE',points:aeLosses.map((v,i)=>[i,v])},{label:'一维噪声预测',points:diffusionLosses.map((v,i)=>[i,v])}]},curve('一维反向采样轨迹',trajectory)],{weights:w,initial,aeLosses,diffusionLosses,noiseWeights:theta,trajectory,predictedNoise,reconstructed},[{label:'AE最终损失',value:aeLosses.at(-1)},{label:'噪声预测MSE',value:diffusionLosses.at(-1)}],'玩具线性AE及一维学习噪声预测器：输出是标量轨迹，不是大型图像扩散模型。',[scatter('初始AE重建',points.map(p=>{let z=initial[0]*p[0]+initial[1]*p[1];return [initial[2]*z,initial[3]*z]})),curve('前10轮噪声损失',diffusionLosses.slice(0,11)),curve('采样前半段',trajectory.slice(0,11))])}),
make('05','玩具图文特征对齐与零样本余弦','177–213','优化配对特征投影并用余弦对未训练组合分类。','合成颜色/方向图像特征与人工文本属性映射到同一二维空间；均方配对误差与锚定项防止坍缩。',[control('steps','优化轮数',50,1000,50,400)],({params,seed})=>{let r=rng(seed),imageW=Array.from({length:4},()=>r()-.5),textW=Array.from({length:4},()=>r()-.5),initial={image:imageW.slice(),text:textW.slice()},pairs=[[[1,0],[1,0]],[[0,1],[0,1]],[[-1,0],[-1,0]],[[0,-1],[0,-1]]],project=(w,x)=>[w[0]*x[0]+w[1]*x[1],w[2]*x[0]+w[3]*x[1]],losses=[];for(let t=0;t<=params.steps;t++){let gi=[0,0,0,0],gt=[0,0,0,0],loss=0;for(let [im,tx]of pairs){let a=project(imageW,im),b=project(textW,tx);for(let j=0;j<2;j++){let e=a[j]-b[j],ai=a[j]-im[j],bt=b[j]-tx[j];loss+=e*e+.5*(ai*ai+bt*bt);for(let k=0;k<2;k++){gi[j*2+k]+=(2*e+ai)*im[k]/4;gt[j*2+k]+=(-2*e+bt)*tx[k]/4}}}losses.push(loss/4);if(t<params.steps){imageW=imageW.map((v,j)=>v-.1*gi[j]);textW=textW.map((v,j)=>v-.1*gt[j])}}let query=[.8,.6],candidates=[[1,0],[0,1],[-1,0],[0,-1]],z=project(imageW,query),cosines=candidates.map(c=>{let v=project(textW,c);return dot(z,v)/Math.max(1e-12,Math.sqrt(dot(z,z)*dot(v,v)))}),predicted=cosines.indexOf(Math.max(...cosines));return result([scatter('人工配对属性',pairs.map(([x],i)=>[...x,i])),curve('配对与锚定真实损失',losses),bars('未训练组合的余弦分数',cosines,['颜色A','方向B','颜色反向','方向反向'])],{imageW,textW,initial,losses,query,cosines,predicted},[{label:'最大余弦',value:Math.max(...cosines)}],'玩具人工属性对齐：不读取自然语言，不是CLIP/VLM；零样本仅指该组合未出现在训练配对中。',[scatter('初始图像投影',pairs.map(([x],i)=>[...project(initial.image,x),i])),curve('前10轮损失',losses.slice(0,11)),scatter('训练后的文本投影',candidates.map((x,i)=>[...project(textW,x),i]))])})];
const teaching=[
{steps:['在40个源域合成样本上真实预训练小网络。','调整目标域平移并复制预训练权重，分别冻结隐藏层和微调全网。','对照目标域损失与参数变化，检查冻结权重是否完全不变。'],questions:['为什么目标域平移可能造成负迁移？','冻结隐藏层降低训练成本时牺牲了哪些适应能力？'],failure:'目标域平移越大，源域特征可能越不合适；训练轮数过少时源域本身未充分训练。'},
{steps:['查看三组候选框分数，按分数排序进行真实NMS。','调整IoU阈值，观察保留框索引的变化。','移动预测掩码，计算像素交集、并集及IoU和Dice。'],questions:['NMS阈值变大为什么通常保留更多重叠框？','Dice与IoU使用同一交集时为什么数值不同？'],failure:'NMS阈值过低可能抑制相邻目标；掩码位移过大产生边界裁切，IoU明显下降。'},
{steps:['把4×4图像拆成四个2×2 patch并检查4×4特征矩阵。','改变QK投影尺度，计算缩放点积与每行softmax。','检查权重行和为1，并用4×2 V算出4×2输出。'],questions:['QK尺度增大为何使注意力分布变尖锐？','patch数翻倍时注意力矩阵元素数量怎样变化？'],failure:'QK尺度过大会使权重集中在少数token；本固定投影没有位置编码学习或语义能力。'},
{steps:['训练2→1→2瓶颈AE并观察实际重建损失。','用合成一维加噪样本优化多项式噪声预测器。','改变初始采样噪声，执行20步反向采样并比较标量轨迹。'],questions:['线性AE的一维瓶颈为什么适合这组共线样本？','噪声预测损失下降为什么不能证明能生成真实图像？'],failure:'训练轮数过少时噪声预测不充分；极端初始噪声可能超出合成训练分布，反向轨迹不可靠。'},
{steps:['查看四组人工图像/文本属性配对。','优化两侧二维投影的配对损失与防坍缩锚定项。','将未训练属性组合投影后计算与四类候选的真实余弦。'],questions:['如果只有配对距离而没有锚定，为什么可能全部坍缩到零？','未训练组合的余弦分类与真正自然语言零样本识别有何区别？'],failure:'训练轮数太少可能未对齐；属性表不包含自然语言和真实图像，无法推断开放词汇语义。'}];
scenes.forEach((s,i)=>Object.assign(s,teaching[i]));
chapter.sections[0].overview+=' ResNet的残差连接与预训练骨干常用于迁移；本实验的小网络不实现ResNet。';
chapter.sections[2].overview+=' ViT以patch为token；窗口注意力限制局部交互以降低开销，需要跨窗口连接传播全局信息。';
chapter.sections[3].overview+=' VAE通过潜变量分布与KL约束学习生成表示；GAN通过生成器/判别器对抗学习，训练可能不稳定。二者在本章仅作概念对照。';
chapter.sections.splice(2,0,{title:'自监督学习（概览）',pages:'61–79',relatedScene:'05',overview:'从数据本身构造监督信号，包括对比学习、掩码重建和代理任务；不需要人工类别标签，但仍依赖数据与增强策略。实验05仅以人工属性配对展示对齐，未实现完整自监督训练。',conditions:'适合未标注数据丰富的情境；增强必须保留任务相关信息，避免错误正负样本。'});
chapter.sections.splice(4,0,{title:'DETR（概览）',pages:'120–136',relatedScene:'02',overview:'Transformer检测将候选目标视为集合，使用可学习query、集合预测与二分匹配损失；区别于依赖NMS的候选框流程。实验02只计算框与NMS，未实现DETR。',conditions:'需要检测标注、足够训练资源与集合匹配；不能由几何IoU演示推断模型性能。'});
chapter.sections.push({title:'系统研究与应用（概览）',pages:'215–234',relatedScene:'01',overview:'综合数据、模型、训练、评价与部署约束开展系统研究；检查复现、消融、分布变化和算力成本，用证据区分机制展示与应用效果。',conditions:'明确真实目标、独立评价数据及资源预算后再选模型；这些合成实验仅用于理解机制。'});
chapter.sections.forEach(s=>{s.conditions??='在明确数据假设与独立评价需求时使用；相关实验是合成机制展示，不能替代真实任务验证。'});
