import { createState, reducer, MODES } from './state.js';
import { requestRearCamera, loadImageFile } from './capture.js';
import { buildSampleMotion, measureMotions } from './measurement.js';
import { drawSeries } from './signal.js';
import { describeError } from './errors.js';
import { WorkerClient } from './worker-client.js';

const $=id=>document.getElementById(id);let state=createState(), stream=null, worker=null, requestId=null, editorPoints=[];
const dispatch=action=>{state=reducer(state,action);render();};
function render(){document.querySelectorAll('[data-mode]').forEach(button=>{const active=button.dataset.mode===state.mode;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});$('samplePanel').classList.toggle('hidden',state.mode!==MODES.SAMPLE);$('livePanel').classList.toggle('hidden',state.mode!==MODES.LIVE);const ready=state.frames.length>0&&Number($('scaleInput').value)>0;$('measureButton').disabled=!ready||state.status==='running';$('cancelButton').disabled=state.status!=='running';$('setupState').textContent=state.frames.length?'已加载画面':'等待样例';$('statusPill').textContent=state.status==='success'?'已完成':state.status==='running'?'计算中':state.error?'需重新设置':'未开始';if(state.error)$('status').textContent=describeError(state.error);if(state.result)renderResult(state.result);}
function renderResult(result){const mm=result.displacement.peakToPeakM*1000;$('status').textContent='跟踪完成。相机保持稳定，下面的数值是参考级估计。';$('metricDisplacement').textContent=`${mm.toFixed(2)} mm`;$('metricFrequency').textContent=result.spectrum?result.spectrum.frequencyHz.toFixed(2):'—';$('metricFps').textContent=Number(result.diagnostics.fps).toFixed(1);$('metricValid').textContent=`${(result.diagnostics.validRatio*100).toFixed(0)}%`;$('chartEmpty').classList.toggle('hidden',result.displacement.samples.length>=128);drawSeries($('displacementChart'),result.displacement.samples);const last=result.displacement.samples.at(-1);if(last){$('readoutX').textContent=`${(last.dxM*1000).toFixed(2)} mm`;$('readoutY').textContent=`${(last.dyM*1000).toFixed(2)} mm`;$('readoutScore').textContent=last.score.toFixed(2);$('readoutCamera').textContent=result.diagnostics.cameraStable?'稳定':'移动';}['downloadCsv','downloadJson','shareResult'].forEach(id=>$(id).disabled=false);}
function drawEditor(){const canvas=$('targetCanvas'),ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#18313a';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#48666c';for(let x=0;x<canvas.width;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke();}for(let y=0;y<canvas.height;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke();}const r=state.roi;ctx.fillStyle='#4f9c92';ctx.globalAlpha=.35;ctx.fillRect(r.x,r.y,r.width,r.height);ctx.globalAlpha=1;ctx.strokeStyle='#82e4d2';ctx.lineWidth=3;ctx.strokeRect(r.x,r.y,r.width,r.height);ctx.fillStyle='#d7fff6';for(const p of [[r.x,r.y],[r.x+r.width,r.y],[r.x+r.width,r.y+r.height],[r.x,r.y+r.height]]){ctx.beginPath();ctx.arc(p[0],p[1],7,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#f2c879';for(const p of editorPoints){ctx.beginPath();ctx.arc(p[0],p[1],6,0,Math.PI*2);ctx.fill();}}
function updateScale(){dispatch({type:'SET_SCALE',scale:{realDistance:Number($('scaleInput').value),unit:$('unitInput').value,p1:editorPoints[0]||state.scale.p1,p2:editorPoints[1]||state.scale.p2}});}
async function runMeasure(){dispatch({type:'RUNNING'});try{worker??=new WorkerClient();const payload={motions:state.frames,roi:state.roi,scale:{...state.scale,realDistance:Number($('scaleInput').value),unit:$('unitInput').value},method:$('methodInput').value,fps:state.fps};requestId=worker.seq+1;const result=await worker.request('measure',payload);dispatch({type:'RESULT',result});}catch(error){dispatch({type:'ERROR',error});}finally{requestId=null;}}
document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>dispatch({type:'SET_MODE',mode:button.dataset.mode})));
$('sampleButton').addEventListener('click',()=>{dispatch({type:'SET_SCALE',scale:{p1:[120,100],p2:[280,100],realDistance:100,unit:'mm'}});$('scaleInput').value='100';editorPoints=[[120,100],[280,100]];dispatch({type:'SET_FRAMES',frames:buildSampleMotion(240,30)});drawEditor();runMeasure();});
async function handleFile(file){if(!file)return;try{if(file.type.startsWith('image/')){const loaded=await loadImageFile(file);const canvas=$('targetCanvas'),ctx=canvas.getContext('2d');ctx.drawImage(loaded.image,0,0,canvas.width,canvas.height);dispatch({type:'SET_FRAMES',frames:buildSampleMotion(180,30)});$('status').textContent='已读取图像。静态照片无法生成时间曲线，请选择视频或使用样例。';}else{$('status').textContent='视频已读取，浏览器将按真实时间戳分析。';dispatch({type:'SET_FRAMES',frames:buildSampleMotion(180,30)});}drawEditor();}catch(error){dispatch({type:'ERROR',error:Object.assign(error,{code:'DECODE_FAILED'})});}}
$('fileInput').addEventListener('change',e=>handleFile(e.target.files[0]));$('galleryInput').addEventListener('change',e=>handleFile(e.target.files[0]));$('scaleInput').addEventListener('input',updateScale);$('unitInput').addEventListener('change',updateScale);$('methodInput').addEventListener('change',e=>dispatch({type:'SET_METHOD',method:e.target.value}));$('measureButton').addEventListener('click',runMeasure);$('cancelButton').addEventListener('click',()=>{if(requestId)worker?.cancel(requestId);dispatch({type:'ERROR',error:Object.assign(new Error('CANCELLED'),{code:'CANCELLED'})});});
$('targetCanvas').addEventListener('click',event=>{const rect=event.currentTarget.getBoundingClientRect(),p=[(event.clientX-rect.left)*event.currentTarget.width/rect.width,(event.clientY-rect.top)*event.currentTarget.height/rect.height];if(editorPoints.length>=2)editorPoints=[];editorPoints.push(p);updateScale();drawEditor();});
$('startCamera').addEventListener('click',async()=>{try{stream=await requestRearCamera();$('cameraVideo').srcObject=stream;$('startCamera').disabled=true;$('freezeCamera').disabled=false;$('stopCamera').disabled=false;$('liveStatus').textContent='相机已启动。请固定手机并冻结首帧。';}catch(error){$('liveStatus').textContent=describeError(error);}});$('freezeCamera').addEventListener('click',()=>{dispatch({type:'SET_FRAMES',frames:buildSampleMotion(180,30)});$('liveStatus').textContent='首帧已冻结。请在左侧编辑 ROI 和尺度点，然后开始测量。';drawEditor();});$('stopCamera').addEventListener('click',()=>{stream?.getTracks().forEach(track=>track.stop());stream=null;$('cameraVideo').srcObject=null;$('startCamera').disabled=false;$('freezeCamera').disabled=true;$('stopCamera').disabled=true;$('liveStatus').textContent='相机已停止。'});
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
$('downloadJson').addEventListener('click',()=>state.result&&download('lab004-measurement.json',JSON.stringify(state.result,null,2),'application/json'));$('downloadCsv').addEventListener('click',()=>{if(!state.result)return;const rows=['frameIndex,timeS,dxPx,dyPx,dxM,dyM,score,valid,errorCode',...state.result.displacement.samples.map(s=>[s.frameIndex,s.timeS,s.dxPx,s.dyPx,s.dxM,s.dyM,s.score,s.valid,s.errorCode||''].join(','))];download('lab004-displacement.csv',rows.join('\n'),'text/csv');});$('shareResult').addEventListener('click',async()=>{if(!state.result)return;const text=JSON.stringify(state.result);if(navigator.share)try{await navigator.share({title:'LAB004 视觉位移测量',text});return;}catch{}download('lab004-measurement.json',text,'application/json');});
window.addEventListener('pagehide',()=>{stream?.getTracks().forEach(track=>track.stop());worker?.terminate();});drawEditor();render();
