import { createState, reducer, MODES } from './state.js';
import { requestRearCamera, videoFrames, captureLiveFrames, motionFromFramesFlowRansac } from './capture.js';
import { buildSampleFrames, measureMotions } from './measurement.js';
import { metresPerPixel } from './contracts.js';
import { ERROR_MESSAGES } from './contracts.js';
import { clampRoi, moveRoi, resizeRoi, nearestRoiHandle, roiContains } from './editor.js';

const $ = (id) => document.getElementById(id); let state = createState(); let stream = null; let editorFrame = null; let frames = []; let scalePoints = [[80, 300], [280, 300]]; let roi = { ...state.roi }; let mode = MODES.SAMPLE; let cancelled = false; let sampleSpeed = 1; let roiDrag = null;
function setStatus(text, error = false) { $('status').textContent = text; $('statusPill').textContent = error ? '需要重试' : text.includes('完成') ? '完成' : '准备中'; }
function clearRenderedResult() { ['metricVelocity','metricVelocityKmh','metricDirection','metricMeanSpeed','metricPeakSpeed','metricValid'].forEach((id) => { const node = $(id); if (node) node.textContent = '—'; }); $('diagnosticsText').textContent = '尚未运行'; const chart = $('speedChart'); chart.getContext('2d').clearRect(0, 0, chart.width, chart.height); $('chartEmpty').classList.remove('hidden'); ['downloadJson','downloadCsv','shareResult'].forEach((id) => { $(id).disabled = true; }); }
function drawEditor() { const canvas = $('targetCanvas'); const ctx = canvas.getContext('2d'); ctx.clearRect(0, 0, canvas.width, canvas.height); if (editorFrame) ctx.drawImage(editorFrame, 0, 0, canvas.width, canvas.height); else { ctx.fillStyle = '#10252d'; ctx.fillRect(0, 0, 640, 360); ctx.fillStyle = '#86e4d2'; ctx.font = '18px sans-serif'; ctx.fillText('等待样例、视频或冻结首帧', 210, 180); } ctx.strokeStyle = '#86e4d2'; ctx.lineWidth = 3; ctx.strokeRect(roi.x, roi.y, roi.width, roi.height); ctx.fillStyle = '#86e4d2'; [[roi.x, roi.y], [roi.x + roi.width, roi.y], [roi.x + roi.width, roi.y + roi.height], [roi.x, roi.y + roi.height]].forEach(([x, y]) => { ctx.beginPath(); ctx.arc(x, y, 7, 0, Math.PI * 2); ctx.fill(); }); ctx.fillStyle = '#ef9d65'; scalePoints.forEach(([x, y], i) => { ctx.beginPath(); ctx.arc(x, y, 8, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#fff'; ctx.fillText(`P${i + 1}`, x + 10, y - 8); ctx.fillStyle = '#ef9d65'; }); }
function updateSetup() { const validScale = (() => { try { metresPerPixel(scalePoints[0], scalePoints[1], $('scaleInput').value, $('unitInput').value); return true; } catch { return false; } })(); const sourceReady = frames.length >= 2 || (mode === MODES.LIVE && editorFrame && stream); $('measureButton').disabled = !(sourceReady && validScale && roi.width >= 32 && roi.height >= 32); $('setupState').textContent = frames.length ? `${frames.length} 帧已准备` : (mode === MODES.LIVE ? (editorFrame ? '首帧已冻结' : '等待相机') : '等待样例或视频'); $('scaleInput').setAttribute('aria-invalid', validScale ? 'false' : 'true'); $('setupChecklist').textContent = sourceReady ? `${frames.length ? `已加载 ${frames.length} 帧。` : '实时画面已准备。'}${validScale ? '尺度有效，可以开始测速。' : '请设置两点实测距离。'}` : '先使用样例、导入视频，或启动相机并冻结首帧。'; }
function drawChart(samples) { const canvas = $('speedChart'); const ctx = canvas.getContext('2d'); ctx.clearRect(0, 0, canvas.width, canvas.height); if (!samples?.length) return; const max = Math.max(...samples.map((s) => s.velocityMps || 0), 1e-6); ctx.strokeStyle = '#71d1c3'; ctx.lineWidth = 3; ctx.beginPath(); samples.forEach((s, i) => { const x = i / Math.max(1, samples.length - 1) * canvas.width; const y = canvas.height - (s.velocityMps / max) * (canvas.height - 20) - 10; i ? ctx.lineTo(x, y) : ctx.moveTo(x, y); }); ctx.stroke(); $('chartEmpty').classList.add('hidden'); }
function renderResult(result) { $('metricVelocity').textContent = result.velocityMps.toFixed(3); $('metricVelocityKmh').textContent = result.velocityKmh.toFixed(2); $('metricDirection').textContent = result.directionDeg.toFixed(1); $('metricMeanSpeed').textContent = result.meanSpeedMps.toFixed(3); $('metricPeakSpeed').textContent = result.peakSpeedMps.toFixed(3); $('metricValid').textContent = `${(result.validRatio * 100).toFixed(0)}%`; $('diagnosticsText').textContent = JSON.stringify(result.diagnostics, null, 2); drawChart(result.samples); $('downloadJson').disabled = false; $('downloadCsv').disabled = false; $('shareResult').disabled = false; setStatus('测速完成：这是参考级表观速度，不代表 GPS 地速。'); }
function scale() { return { p1: scalePoints[0], p2: scalePoints[1], realDistance: Number($('scaleInput').value), unit: $('unitInput').value }; }
async function run() { cancelled = false; state = reducer(state, { type: 'RUNNING' }); $('measureButton').disabled = true; $('cancelButton').disabled = false; setStatus('正在用 LK 光流和 RANSAC 跟踪静止世界……'); try { if (mode === MODES.LIVE && editorFrame && !frames.length) { const captured = await captureLiveFrames($('cameraVideo'), { durationMs: 4000, shouldCancel: () => cancelled }); frames = [{ ...editorFrame, source: 'camera', timeS: 0 }, ...captured.frames]; state.fps = captured.fps; } if (frames.length < 2) throw Object.assign(new Error('INVALID_FRAME'), { code: 'INVALID_FRAME' }); const motions = motionFromFramesFlowRansac(frames, roi, state.fps || 30); if (cancelled) throw Object.assign(new Error('CANCELLED'), { code: 'CANCELLED' }); const result = measureMotions(motions, { roi, scale: scale(), fps: state.fps || 30 }); state = reducer(state, { type: 'RESULT', result }); renderResult(result); } catch (error) { state = reducer(state, { type: 'ERROR', error }); setStatus(ERROR_MESSAGES[error.code] || error.message || '测速失败。', true); } finally { $('measureButton').disabled = false; $('cancelButton').disabled = true; updateSetup(); } }
async function importVideo(file) { clearRenderedResult(); setStatus('正在读取视频……'); try { const result = await videoFrames(file, { maxFrames: 180, onProgress: (v) => setStatus(`正在读取视频……${Math.round(v * 100)}%`) }); frames = result.frames; state = reducer(state, { type: 'SET_FRAMES', frames }); state.fps = result.fps; editorFrame = frames[0].canvas; drawEditor(); updateSetup(); setStatus(`已读取 ${frames.length} 帧视频，请拖动四角框选静止纹理并设置尺度。`); } catch (error) { clearRenderedResult(); setStatus(ERROR_MESSAGES[error.code] || '无法读取视频。', true); } }
document.querySelectorAll('[data-mode]').forEach((button) => button.addEventListener('click', () => { clearRenderedResult(); mode = button.dataset.mode; document.querySelectorAll('[data-mode]').forEach((b) => b.classList.toggle('active', b === button)); $('samplePanel').classList.toggle('hidden', mode !== MODES.SAMPLE); $('livePanel').classList.toggle('hidden', mode !== MODES.LIVE); frames = []; editorFrame = null; state = reducer(state, { type: 'SET_MODE', mode }); drawEditor(); updateSetup(); setStatus(mode === MODES.LIVE ? '启动后置相机，冻结首帧后再设置区域。' : '点击“用样例体验”，或导入 MP4/WebM。'); }));
$('sampleButton').addEventListener('click', () => { clearRenderedResult(); frames = buildSampleFrames(180, 30, sampleSpeed); editorFrame = frames[0].canvas; state = reducer(state, { type: 'SET_FRAMES', frames }); state.fps = 30; roi = { x: 160, y: 90, width: 320, height: 180 }; scalePoints = [[80, 300], [280, 300]]; $('scaleInput').value = '1'; $('unitInput').value = 'm'; drawEditor(); updateSetup(); run(); });
$('fileInput').addEventListener('change', (e) => { if (e.target.files[0]) importVideo(e.target.files[0]); e.target.value = ''; }); $('galleryInput').addEventListener('change', (e) => { if (e.target.files[0]) importVideo(e.target.files[0]); e.target.value = ''; });
$('scaleInput').addEventListener('input', updateSetup); $('unitInput').addEventListener('change', updateSetup); $('measureButton').addEventListener('click', run); $('cancelButton').addEventListener('click', () => { cancelled = true; clearRenderedResult(); setStatus('测量已取消。'); }); $('resetButton').addEventListener('click', () => { clearRenderedResult(); frames = []; editorFrame = null; state = reducer(state, { type: 'CLEAR' }); drawEditor(); updateSetup(); setStatus('已清空，请重新选择样例、视频或启动相机。'); });
function canvasPoint(event) { const box = event.currentTarget.getBoundingClientRect(); return { x: (event.clientX - box.left) / box.width * 640, y: (event.clientY - box.top) / box.height * 360 }; }
$('targetCanvas').addEventListener('pointerdown', (event) => { const point = canvasPoint(event); const handle = nearestRoiHandle(point, roi); if (handle >= 0) roiDrag = { mode: 'resize', handle, point }; else if (roiContains(point, roi)) roiDrag = { mode: 'move', point }; else { scalePoints = scalePoints.length >= 2 ? [[point.x, point.y]] : [...scalePoints, [point.x, point.y]]; drawEditor(); updateSetup(); return; } event.currentTarget.setPointerCapture?.(event.pointerId); event.preventDefault(); });
$('targetCanvas').addEventListener('pointermove', (event) => { if (!roiDrag) return; const point = canvasPoint(event); const delta = { x: point.x - roiDrag.point.x, y: point.y - roiDrag.point.y }; roi = roiDrag.mode === 'resize' ? resizeRoi(roi, roiDrag.handle, delta) : moveRoi(roi, delta); roiDrag.point = point; drawEditor(); updateSetup(); });
$('targetCanvas').addEventListener('pointerup', () => { roiDrag = null; });
$('startCamera').addEventListener('click', async () => { try { stream = await requestRearCamera(); $('cameraVideo').srcObject = stream; await $('cameraVideo').play(); $('startCamera').disabled = true; $('freezeCamera').disabled = false; $('stopCamera').disabled = false; $('liveStatus').textContent = '相机已启动。固定手机后点击冻结首帧。'; } catch (error) { $('liveStatus').textContent = ERROR_MESSAGES[error.code] || '相机不可用，请导入视频。'; } });
$('freezeCamera').addEventListener('click', () => { const video = $('cameraVideo'); const canvas = document.createElement('canvas'); canvas.width = 640; canvas.height = 360; canvas.getContext('2d').drawImage(video, 0, 0, 640, 360); editorFrame = canvas; frames = []; state = reducer(state, { type: 'CLEAR' }); drawEditor(); $('liveStatus').textContent = '首帧已冻结。设置区域和尺度后点击开始测速。'; updateSetup(); });
$('stopCamera').addEventListener('click', () => { stream?.getTracks().forEach((track) => track.stop()); stream = null; $('cameraVideo').srcObject = null; $('startCamera').disabled = false; $('freezeCamera').disabled = true; $('stopCamera').disabled = true; });
document.querySelectorAll('[data-challenge]').forEach((button) => button.addEventListener('click', () => { sampleSpeed = button.dataset.challenge === 'slow' ? .5 : button.dataset.challenge === 'fast' ? 2 : 1; $('sampleSource').textContent = button.dataset.challenge === 'texture' ? '换用地砖、砖墙和白墙比较纹理差异。' : `${button.textContent}：观察速度读数和有效比例。`; $('sampleButton').click(); }));
function download(name, text, type) { const url = URL.createObjectURL(new Blob([text], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
$('downloadJson').addEventListener('click', () => state.result && download('lab004-speed-report.json', JSON.stringify(state.result, null, 2), 'application/json')); $('downloadCsv').addEventListener('click', () => state.result && download('lab004-speed.csv', ['frameIndex,timeS,velocityMps,velocityKmh,directionDeg,confidence,valid,errorCode', ...state.result.samples.map((s) => [s.frameIndex, s.timeS, s.velocityMps, s.velocityKmh, s.directionDeg, s.confidence, s.valid, s.errorCode || ''].join(','))].join('\n'), 'text/csv')); $('shareResult').addEventListener('click', async () => { if (!state.result) return; const text = JSON.stringify(state.result); if (navigator.share) try { await navigator.share({ title: 'LAB004 静止世界速度计', text }); return; } catch {} download('lab004-speed-report.json', text, 'application/json'); });
window.addEventListener('pagehide', () => { stream?.getTracks().forEach((track) => track.stop()); }); drawEditor(); updateSetup();
