let cvPromise;
let trackSession;
let trackBadFrames=0;
const cancelled = new Set();
const STABLE_MAX_NORMALIZED_RMS = .0015;
const REFERENCE_ONLY_MAX_NORMALIZED_RMS = .0035;
const POSE_AMBIGUITY_MAX_ABSOLUTE_DIFFERENCE_PX = .25;
const POSE_AMBIGUITY_MAX_RELATIVE_DIFFERENCE = .10;
const UNCERTAINTY_INTERVAL_MS = 500;
let lastUncertainty = 0;
const positiveCameraCenterZ = center => center[2] > 0;

async function loadRuntime(){
  if(!cvPromise) cvPromise=import('../vendor/opencv.js').then(m=>(m.default||m.cv||m)()).catch(()=>{const e=new Error('BUILD_PREREQUISITE');e.code='BUILD_PREREQUISITE';throw e;});
  return cvPromise;
}
const own=(list,value)=>(list.push(value),value);
function checkCancelled(id){if(cancelled.has(id)){const e=new Error('CANCELLED');e.code='CANCELLED';throw e;}}
function quality(r){return r<=STABLE_MAX_NORMALIZED_RMS?'stable':r<=REFERENCE_ONLY_MAX_NORMALIZED_RMS?'reference-only':'unstable';}
function matrix(cv,rows,cols,values){const m=new cv.Mat(rows,cols,cv.CV_64F);m.data64F.set(values);return m;}
function eulerZYX(r){const y=Math.asin(Math.max(-1,Math.min(1,-r[6])));return Math.abs(Math.cos(y))>1e-9?[Math.atan2(r[3],r[0]),y,Math.atan2(r[7],r[8])]:[Math.atan2(-r[1],r[4]),y,0];}
function evaluateCandidate(cv,object,image,camera,dist,rv,tv,size,owned){
  const rotation=own(owned,new cv.Mat());cv.Rodrigues(rv,rotation);const r=[...rotation.data64F],t=[...tv.data64F];
  const center=[-(r[0]*t[0]+r[3]*t[1]+r[6]*t[2]),-(r[1]*t[0]+r[4]*t[1]+r[7]*t[2]),-(r[2]*t[0]+r[5]*t[1]+r[8]*t[2])];
  if(!r.every(Number.isFinite)||!t.every(Number.isFinite)||center[2]<=1e-9)return null;
  for(let i=0;i<object.rows;i++){const z=r[6]*object.data64F[i*3]+r[7]*object.data64F[i*3+1]+r[8]*object.data64F[i*3+2]+t[2];if(!Number.isFinite(z)||z<=1e-9)return null;}
  const projected=own(owned,new cv.Mat());cv.projectPoints(object,rv,tv,camera,dist,projected);const p=[...projected.data64F],q=[...image.data64F];const rms=Math.sqrt(p.reduce((sum,v,i)=>sum+(v-q[i])**2,0)/4);return {rvec:[...rv.data64F],tvec:t,rotation:r,center,rms,normalizedRms:rms/Math.hypot(...size),quality:quality(rms/Math.hypot(...size)),euler:eulerZYX(r)};
}
function uncertainty(base,data,id){if(!base||!Number.isFinite(base.perpendicularDistanceM))return null;const values=[];for(let i=0;i<64;i++){checkCancelled(id);const dx=((i*37)%17-8)*.03,dy=((i*19)%13-6)*.03,df=1+(((i*23)%29)-14)*.001;const nominal=Math.hypot(data.quad[1][0]-data.quad[0][0],data.quad[1][1]-data.quad[0][1]);const perturbed=Math.hypot(data.quad[1][0]-data.quad[0][0]+dx,data.quad[1][1]-data.quad[0][1]+dy);values.push(base.perpendicularDistanceM*(nominal/perturbed)*df);}if(!values.every(Number.isFinite))return null;values.sort((a,b)=>a-b);return {medianM:values[32],lowerM:values[3],upperM:values[60],confidence:.9};}
function solvePose(cv,data,owned,id){
  checkCancelled(id);const {quad,target,intrinsics}=data;const size=data.imageSizePx;const [width,height]=size;const halfW=target.widthM/2,halfH=target.heightM/2;const f=intrinsics?.cameraMatrix?.[0]?.[0]||Math.max(width,height);
  const object=own(owned,matrix(cv,4,3,[-halfW,halfH,0,halfW,halfH,0,halfW,-halfH,0,-halfW,-halfH,0]));const image=own(owned,matrix(cv,4,2,quad.flat()));const camera=own(owned,matrix(cv,3,3,intrinsics?.cameraMatrix?.flat()||[f,0,width/2,0,f,height/2,0,0,1]));const dist=own(owned,matrix(cv,5,1,intrinsics?.distortion||[0,0,0,0,0]));
  const rotations=own(owned,new cv.MatVector()),translations=own(owned,new cv.MatVector());cv.solvePnPGeneric(object,image,camera,dist,rotations,translations,false,cv.SOLVEPNP_IPPE);const candidates=[];for(let i=0;i<rotations.size();i++){checkCancelled(id);const c=evaluateCandidate(cv,object,image,camera,dist,rotations.get(i),translations.get(i),size,owned);if(c)candidates.push(c);}if(!candidates.length){const e=new Error('POSE_FAILED');e.code='POSE_FAILED';throw e;}candidates.sort((a,b)=>a.rms-b.rms);const best=candidates[0];const plausible=candidates.filter(c=>{const d=Math.max(0,c.rms-best.rms);return d<=POSE_AMBIGUITY_MAX_ABSOLUTE_DIFFERENCE_PX||(best.rms>1e-12&&d/best.rms<=POSE_AMBIGUITY_MAX_RELATIVE_DIFFERENCE);});if(plausible.length>1){const e=new Error('POSE_AMBIGUOUS');e.code='POSE_AMBIGUOUS';throw e;}
  const rvec=own(owned,matrix(cv,3,1,best.rvec)),tvec=own(owned,matrix(cv,3,1,best.tvec));cv.solvePnPRefineLM(object,image,camera,dist,rvec,tvec);const refined=evaluateCandidate(cv,object,image,camera,dist,rvec,tvec,size,owned);if(!refined||refined.quality==='unstable'){const e=new Error('HIGH_REPROJECTION_ERROR');e.code='HIGH_REPROJECTION_ERROR';throw e;}const interval=data.liveMode&&Date.now()-lastUncertainty<UNCERTAINTY_INTERVAL_MS?null:uncertainty({perpendicularDistanceM:refined.center[2]},data,id);if(interval||!data.liveMode)lastUncertainty=Date.now();return {rotationMatrix:[refined.rotation.slice(0,3),refined.rotation.slice(3,6),refined.rotation.slice(6,9)],rotationVector:refined.rvec,translationM:refined.tvec,cameraCenterM:refined.center,eulerZYXRad:refined.euler,perpendicularDistanceM:refined.center[2],targetCenterDistanceM:Math.hypot(...refined.center),horizontalOffsetM:refined.center[0],verticalOffsetM:refined.center[1],reprojectionRmsPx:refined.rms,normalizedRms:refined.normalizedRms,quality:refined.quality,calibrationSource:intrinsics?.source||'estimated',distanceInterval:interval,coordinateTransform:data.displayToAnalysis?{analysisToDisplay:1/data.displayToAnalysis}:null};
}
function bitmapGray(cv,bitmap,owned){const canvas=new OffscreenCanvas(bitmap.width,bitmap.height),ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0);const rgba=own(owned,cv.matFromArray(bitmap.height,bitmap.width,cv.CV_8UC4,Array.from(ctx.getImageData(0,0,bitmap.width,bitmap.height).data)));const gray=own(owned,new cv.Mat());cv.cvtColor(rgba,gray,cv.COLOR_RGBA2GRAY);return gray;}
function bad(code='TRACKING_LOST'){const e=new Error(code);e.code=code;throw e;}
function track(cv,data,owned,id){checkCancelled(id);if(!data.bitmap)bad();const gray=bitmapGray(cv,data.bitmap,owned);if(!trackSession){const points=own(owned,new cv.Mat());cv.goodFeaturesToTrack(gray,points,300,.01,7);trackSession={gray:gray.clone(),points:points.clone(),quad:data.quad};return {initialized:true,trackedFeatures:points.rows||0,quad:data.quad};}const next=own(owned,new cv.Mat()),back=own(owned,new cv.Mat()),status=own(owned,new cv.Mat()),error=own(owned,new cv.Mat()),backStatus=own(owned,new cv.Mat()),backError=own(owned,new cv.Mat());cv.calcOpticalFlowPyrLK(trackSession.gray,gray,trackSession.points,next,status,error);cv.calcOpticalFlowPyrLK(gray,trackSession.gray,next,backStatus,backError);const src=[],dst=[],fb=[];for(let i=0;i<next.rows;i++){const fwdOk=status.data[i]&&backStatus.data[i];const e=fwdOk?Math.hypot(back.data32F[i*2]-trackSession.points.data32F[i*2],back.data32F[i*2+1]-trackSession.points.data32F[i*2+1]):Infinity;if(fwdOk&&e<=1.5){src.push(trackSession.points.data32F[i*2],trackSession.points.data32F[i*2+1]);dst.push(next.data32F[i*2],next.data32F[i*2+1]);fb.push(e);}}if(src.length<12)bad();const srcMat=own(owned,cv.matFromArray(src.length/2,2,cv.CV_32F,src)),dstMat=own(owned,cv.matFromArray(dst.length/2,2,cv.CV_32F,dst)),mask=own(owned,new cv.Mat()),homography=own(owned,cv.findHomography(srcMat,dstMat,cv.RANSAC,3,mask));if(!homography||homography.empty())bad();const corners=own(owned,cv.matFromArray(4,1,cv.CV_32FC2,data.quad.flat()));cv.perspectiveTransform(corners,corners,homography);const quad=Array.from(corners.data32F).reduce((a,v,i)=>(a[Math.floor(i/2)]??=[]).push(v)&&a,[]);const pose=solvePose(cv,{...data,quad,liveMode:true},owned,id);trackSession={gray:gray.clone(),points:next.clone(),quad};return {...pose,trackedFeatures:src.length/2,homographyInlierRatio:mask.data.filter(Boolean).length/(src.length/2),medianForwardBackwardErrorPx:fb.sort((a,b)=>a-b)[Math.floor(fb.length/2)],quad};}

function resetTrackSession(){trackSession?.gray?.delete?.();trackSession?.points?.delete?.();trackSession=null;trackBadFrames=0;}
function trackFrame(cv,data,owned,id){
  checkCancelled(id);if(!data.bitmap)bad();const gray=bitmapGray(cv,data.bitmap,owned);
  if(!trackSession){const points=own(owned,new cv.Mat());cv.goodFeaturesToTrack(gray,points,300,.01,7);if((points.rows||0)<12)bad('LOW_TEXTURE');trackSession={gray:gray.clone(),points:points.clone(),quad:data.quad,lost:false};const pose=solvePose(cv,{...data,liveMode:true},owned,id);return {...pose,initialized:true,trackedFeatures:points.rows,quad:data.quad};}
  if(trackSession.lost)bad();const next=own(owned,new cv.Mat()),back=own(owned,new cv.Mat()),status=own(owned,new cv.Mat()),flowError=own(owned,new cv.Mat()),backStatus=own(owned,new cv.Mat()),backError=own(owned,new cv.Mat());cv.calcOpticalFlowPyrLK(trackSession.gray,gray,trackSession.points,next,status,flowError);checkCancelled(id);cv.calcOpticalFlowPyrLK(gray,trackSession.gray,next,back,backStatus,backError);
  const src=[],dst=[],fb=[];for(let i=0;i<next.rows;i++){const e=status.data[i]&&backStatus.data[i]?Math.hypot(back.data32F[i*2]-trackSession.points.data32F[i*2],back.data32F[i*2+1]-trackSession.points.data32F[i*2+1]):Infinity;if(e<=1.5){src.push(trackSession.points.data32F[i*2],trackSession.points.data32F[i*2+1]);dst.push(next.data32F[i*2],next.data32F[i*2+1]);fb.push(e);}}
  if(src.length/2<12)bad();const srcMat=own(owned,cv.matFromArray(src.length/2,2,cv.CV_32F,src)),dstMat=own(owned,cv.matFromArray(dst.length/2,2,cv.CV_32F,dst)),mask=own(owned,new cv.Mat()),homography=own(owned,cv.findHomography(srcMat,dstMat,cv.RANSAC,3,mask));if(!homography||homography.empty())bad();const inliers=mask.data.filter(Boolean).length,ratio=inliers/(src.length/2);if(ratio<.6)bad();const corners=own(owned,cv.matFromArray(4,1,cv.CV_32FC2,trackSession.quad.flat())),projected=own(owned,new cv.Mat());cv.perspectiveTransform(corners,projected,homography);const quad=Array.from(projected.data32F).reduce((a,v,i)=>(a[Math.floor(i/2)]??=[]).push(v)&&a,[]);const pose=solvePose(cv,{...data,quad,liveMode:true},owned,id);trackSession.gray.delete();trackSession.points.delete();trackSession={gray:gray.clone(),points:next.clone(),quad,lost:false};fb.sort((a,b)=>a-b);return {...pose,valid:true,trackedFeatures:src.length/2,homographyInlierRatio:ratio,medianForwardBackwardErrorPx:fb[Math.floor(fb.length/2)],quad};
}
function updateTracking(cv,data,owned,id,initialize=false){if(initialize)resetTrackSession();try{const result=trackFrame(cv,data,owned,id);trackBadFrames=0;return result;}catch(error){if(initialize)throw error;trackBadFrames+=1;if(trackBadFrames>=3){if(trackSession)trackSession.lost=true;bad('TRACKING_LOST');}return {valid:false,measurements:null,quad:trackSession?.quad||data.quad,dimQuad:true,consecutiveBadFrames:trackBadFrames,rejectionReason:error.code||'TRACKING_LOST'};}}
function calibrate(cv,data,owned,id){checkCancelled(id);if(!data.views||data.views.length<8)bad('INSUFFICIENT_VIEW_DIVERSITY');const objectPoints=own(owned,new cv.MatVector()),imagePoints=own(owned,new cv.MatVector());for(const view of data.views){if(!view.objectPointsM||!view.imagePointsPx||view.imagePointsPx.length<4)bad('CALIBRATION_FAILED');if(data.path==='enhanced'&&view.gray&&cv.findChessboardCorners){const corners=own(owned,new cv.Mat());if(!cv.findChessboardCorners(view.gray,view.patternSize||new cv.Size(7,5),corners))bad('LOW_TEXTURE');}objectPoints.push_back(matrix(cv,view.objectPointsM.length,3,view.objectPointsM.flat()));imagePoints.push_back(matrix(cv,view.imagePointsPx.length,2,view.imagePointsPx.flat()));}const [width,height]=data.views[0].imageSizePx;const camera=own(owned,matrix(cv,3,3,[width,0,width/2,0,width,height/2,0,0,1])),dist=own(owned,new cv.Mat()),rvecs=own(owned,new cv.MatVector()),tvecs=own(owned,new cv.MatVector());const flags=data.path==='quick'?(cv.CALIB_USE_INTRINSIC_GUESS|cv.CALIB_FIX_ASPECT_RATIO|cv.CALIB_FIX_PRINCIPAL_POINT):0;const rms=cv.calibrateCamera(objectPoints,imagePoints,new cv.Size(width,height),camera,dist,rvecs,tvecs,flags);return {schema:'lab004.camera-intrinsics.v1',version:1,intrinsics:{cameraMatrix:[...camera.data64F].reduce((a,v,i)=>(a[Math.floor(i/3)]??=[]).push(v)&&a,[]),distortion:[...dist.data64F],imageSizePx:[width,height],source:data.path==='enhanced'?'enhanced-calibrated':'quick-calibrated'},metrics:{rmsPx:rms,normalizedRms:rms/Math.hypot(width,height),acceptedViews:data.views.length}};}
async function handle(cv,type,data,owned,id){checkCancelled(id);if(type==='estimate')return solvePose(cv,data,owned,id);if(type==='initTrack')return updateTracking(cv,data,owned,id,true);if(type==='updateTrack')return updateTracking(cv,data,owned,id,false);if(type==='calibrateQuick'||type==='calibrateEnhanced')return calibrate(cv,{...data,path:type==='calibrateEnhanced'?'enhanced':'quick'},owned,id);bad('UNSUPPORTED_CAMERA');}
self.onmessage=async({data})=>{const {type,id,bitmap}=data;if(type==='cancel'){cancelled.add(id);return;}const owned=[];try{const cv=await loadRuntime();if(type==='load')self.postMessage({type,id,result:{loaded:true}});else self.postMessage({type,id,result:await handle(cv,type,data,owned,id)});}catch(error){self.postMessage({type,id,error:{code:error.code||'POSE_FAILED',message:error.message}});}finally{for(const value of owned.reverse())value?.delete?.();bitmap?.close?.();cancelled.delete(id);}};
