export async function requestRearCamera(){if(!navigator.mediaDevices?.getUserMedia)throw Object.assign(new Error('PERMISSION_DENIED'),{code:'PERMISSION_DENIED'});try{return await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},frameRate:{ideal:30,max:30}},audio:false});}catch(error){throw Object.assign(new Error(error.name==='NotAllowedError'?'PERMISSION_DENIED':'UNSUPPORTED_FORMAT'),{code:error.name==='NotAllowedError'?'PERMISSION_DENIED':'UNSUPPORTED_FORMAT'});}}
export function fileToUrl(file){return URL.createObjectURL(file);}
export function sortImageFiles(files){return [...files].sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),undefined,{numeric:true,sensitivity:'base'}));}
export async function loadImageFile(file){const url=fileToUrl(file),image=new Image();image.src=url;try{await image.decode();return {url,image,width:image.naturalWidth,height:image.naturalHeight};}catch(error){URL.revokeObjectURL(url);throw error;}}

function drawContain(source,width=640,height=360){const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.fillStyle='#10252d';ctx.fillRect(0,0,width,height);const sw=source.videoWidth||source.naturalWidth||source.width,sh=source.videoHeight||source.naturalHeight||source.height,scale=Math.min(width/sw,height/sh),dw=sw*scale,dh=sh*scale;ctx.drawImage(source,(width-dw)/2,(height-dh)/2,dw,dh);return canvas;}
export async function imageFrame(file,width=640,height=360){const loaded=await loadImageFile(file);return {canvas:drawContain(loaded.image,width,height),url:loaded.url,source:file.name};}
function waitFor(element,event){return new Promise((resolve,reject)=>{const onEvent=()=>{cleanup();resolve();},onError=()=>{cleanup();reject(new Error('DECODE_FAILED'));},cleanup=()=>{element.removeEventListener(event,onEvent);element.removeEventListener('error',onError);};element.addEventListener(event,onEvent,{once:true});element.addEventListener('error',onError,{once:true});});}
export async function videoFrames(file,{maxFrames=150,width=640,height=360,onProgress=()=>{},shouldCancel=()=>false}={}){const url=fileToUrl(file),video=document.createElement('video');video.preload='auto';video.muted=true;video.playsInline=true;try{const metadata=waitFor(video,'loadedmetadata');video.src=url;await metadata;if(!Number.isFinite(video.duration)||video.duration<=0)throw new Error('DECODE_FAILED');const sourceFps=30;const expectedCount=Math.max(2,Math.round(video.duration*sourceFps)||2);const count=Math.min(maxFrames,expectedCount),frames=[];for(let index=0;index<count;index++){if(shouldCancel())throw Object.assign(new Error('CANCELLED'),{code:'CANCELLED'});const timeS=video.duration*(index/(count-1));const seek=waitFor(video,'seeked');video.currentTime=timeS;await seek;frames.push({canvas:drawContain(video,width,height),source:file.name,timeS});onProgress((index+1)/count);}return {frames,fps:(count-1)/video.duration||30,url,sourceDurationS:video.duration,sampled:count<expectedCount};}catch(error){URL.revokeObjectURL(url);if(error?.code==='CANCELLED')throw error;throw Object.assign(new Error('DECODE_FAILED'),{code:'DECODE_FAILED'});}}
export async function captureLiveFrames(video,{durationMs=4000,maxFrames=150,width=640,height=360,onProgress=()=>{},onFrame=()=>{},shouldCancel=()=>false}={}){if(!video||video.readyState<2||!video.videoWidth)throw Object.assign(new Error('INVALID_FRAME'),{code:'INVALID_FRAME'});const frames=[];const start=performance.now();let lastCapture=-Infinity;return new Promise((resolve,reject)=>{const tick=(now)=>{if(shouldCancel()){reject(Object.assign(new Error('CANCELLED'),{code:'CANCELLED'}));return;}if(now-lastCapture>=1000/30||!frames.length){const frame={canvas:drawContain(video,width,height),source:'camera',timeS:(now-start)/1000};frames.push(frame);lastCapture=now;onProgress(Math.min(1,(now-start)/durationMs));onFrame(frame,{index:frames.length-1,elapsedS:frame.timeS});}if(now-start>=durationMs||frames.length>=maxFrames){const elapsed=Math.max((now-start)/1000,1/30);resolve({frames,fps:(frames.length-1)/elapsed||30});return;}requestAnimationFrame(tick);};requestAnimationFrame(tick);});}
function gray(canvas){const ctx=canvas.getContext('2d',{willReadFrequently:true}),data=ctx.getImageData(0,0,canvas.width,canvas.height).data,output=new Float32Array(canvas.width*canvas.height);for(let i=0,p=0;i<output.length;i++,p+=4)output[i]=.299*data[p]+.587*data[p+1]+.114*data[p+2];return output;}
function patchError(a,b,width,height,dx,dy,roi,step=3){let total=0,count=0;const x0=Math.max(4,Math.floor(roi.x)+4),x1=Math.min(width-4,Math.ceil(roi.x+roi.width)-4),y0=Math.max(4,Math.floor(roi.y)+4),y1=Math.min(height-4,Math.ceil(roi.y+roi.height)-4);for(let y=y0;y<y1;y+=step)for(let x=x0;x<x1;x+=step){const bx=Math.max(0,Math.min(width-1,x+dx)),by=Math.max(0,Math.min(height-1,y+dy));total+=Math.abs(a[y*width+x]-b[by*width+bx]);count++;}return count?total/count:Infinity;}
function findPatchOffset(previous,current,width,height,roi){let best={error:Infinity,dx:0,dy:0};for(let dy=-12;dy<=12;dy+=3)for(let dx=-12;dx<=12;dx+=3){const error=patchError(previous,current,width,height,dx,dy,roi,6);if(error<best.error)best={error,dx,dy};}const coarse=best;for(let dy=coarse.dy-2;dy<=coarse.dy+2;dy++)for(let dx=coarse.dx-2;dx<=coarse.dx+2;dx++){const error=patchError(previous,current,width,height,dx,dy,roi,3);if(error<best.error)best={error,dx,dy};}return best;}
function backgroundAnchors(width,height,roi){const size=56, candidates=[[12,12],[width-size-12,12],[12,height-size-12],[width-size-12,height-size-12]];return candidates.filter(([x,y])=>x+size<roi.x||x>roi.x+roi.width||y+size<roi.y||y>roi.y+roi.height).map(([x,y])=>({x,y,width:size,height:size}));}
function estimateBackgroundShift(previous,current,width,height,roi){const anchors=backgroundAnchors(width,height,roi);if(anchors.length<2)return {trackable:false,drift:Infinity};const shifts=[];for(const anchor of anchors){const values=[];for(let y=anchor.y;y<anchor.y+anchor.height;y+=2)for(let x=anchor.x;x<anchor.x+anchor.width;x+=2)values.push(previous[y*width+x]);const mean=values.reduce((sum,value)=>sum+value,0)/Math.max(1,values.length);const variance=values.reduce((sum,value)=>sum+(value-mean)**2,0)/Math.max(1,values.length);if(variance<12)continue;let best={error:Infinity,dx:0,dy:0};for(let dy=-6;dy<=6;dy++)for(let dx=-6;dx<=6;dx++){const error=patchError(previous,current,width,height,dx,dy,anchor);if(error<best.error)best={error,dx,dy};}if(Number.isFinite(best.error))shifts.push([best.dx,best.dy]);}if(shifts.length<2)return {trackable:false,drift:Infinity};const median=(values)=>values.slice().sort((a,b)=>a-b)[Math.floor(values.length/2)];return {trackable:true,drift:Math.hypot(median(shifts.map((shift)=>shift[0])),median(shifts.map((shift)=>shift[1])))};}
export function motionFromFrames(frames,roi,fps=30,{detectCameraDrift=false}={}){if(!Array.isArray(frames)||frames.length<2)throw Object.assign(new Error('INVALID_FRAME'),{code:'INVALID_FRAME'});const width=frames[0].canvas.width,height=frames[0].canvas.height,scaleX=width/640,scaleY=height/360,scaled={x:roi.x*scaleX,y:roi.y*scaleY,width:roi.width*scaleX,height:roi.height*scaleY};let previous=gray(frames[0].canvas),offsetX=0,offsetY=0;const motions=[{offsetX:0,offsetY:0,score:1,timeS:Number.isFinite(frames[0].timeS)?frames[0].timeS:0,cameraStable:true,backgroundTrackable:true}];for(let i=1;i<frames.length;i++){const current=gray(frames[i].canvas);const best=findPatchOffset(previous,current,width,height,scaled);offsetX+=best.dx/scaleX;offsetY+=best.dy/scaleY;const background=detectCameraDrift?estimateBackgroundShift(previous,current,width,height,scaled):{trackable:true,drift:0};const cameraStable=background.trackable&&background.drift<=1.5;motions.push({offsetX,offsetY,score:cameraStable?Math.max(0,1-best.error/80):0,timeS:Number.isFinite(frames[i].timeS)?frames[i].timeS:i/fps,cameraStable,backgroundTrackable:background.trackable,cameraDriftPx:background.drift,errorCode:!background.trackable?'BACKGROUND_UNTRACKABLE':cameraStable?null:'CAMERA_MOVED'});previous=current;}return motions;}
