"""Standalone planar camera-pose core for LAB 004."""

from .contracts import (
    ANALYSIS_MAX_SIDE,
    CALIBRATION_SCHEMA,
    CORNER_ORDER,
    MAX_WORKING_SET_MIB,
    POSE_AMBIGUITY_MAX_ABSOLUTE_DIFFERENCE_PX,
    POSE_AMBIGUITY_MAX_RELATIVE_DIFFERENCE,
    REFERENCE_ONLY_MAX_NORMALIZED_RMS,
    STABLE_MAX_NORMALIZED_RMS,
    TRACKING_DEFAULTS,
    CalibrationMetrics,
    CalibrationResult,
    CalibrationView,
    CameraIntrinsics,
    ImagePoint,
    MeasurementInterval,
    MeasurementReport,
    PlaneTarget,
    PoseEstimate,
    TrackingMetrics,
)
from .errors import ERROR_CODES, CameraPoseError

__all__ = [
    "ANALYSIS_MAX_SIDE",
    "CALIBRATION_SCHEMA",
    "CORNER_ORDER",
    "ERROR_CODES",
    "CalibrationMetrics",
    "CalibrationResult",
    "CalibrationView",
    "CameraIntrinsics",
    "CameraPoseError",
    "ImagePoint",
    "MeasurementInterval",
    "MeasurementReport",
    "MAX_WORKING_SET_MIB",
    "POSE_AMBIGUITY_MAX_ABSOLUTE_DIFFERENCE_PX",
    "POSE_AMBIGUITY_MAX_RELATIVE_DIFFERENCE",
    "PlaneTarget",
    "PoseEstimate",
    "REFERENCE_ONLY_MAX_NORMALIZED_RMS",
    "STABLE_MAX_NORMALIZED_RMS",
    "TRACKING_DEFAULTS",
    "TrackingMetrics",
]
