import {chromium} from 'playwright';import assert from 'node:assert/strict';
import {createServer} from 'node:http';import {readFile,stat,mkdir,writeFile} from 'node:fs/promises';import {resolve,extname,relative} from 'node:path';
import {sites} from '../independent-sites.mjs';
const root=resolve(import.meta.dirname,'../../work/independent-sites'),qa=resolve(import.meta.dirname,'../../.superpowers/sdd/independent-sites/qa');await mkdir(qa,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.wasm':'application/wasm','.jpg':'image/jpeg','.png':'image/png','.mp4':'video/mp4'};
const server=process.env.INDEPENDENT_ONLINE?null:createServer(async(req,res)=>{try{let p=resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(relative(root,p).startsWith('..'))throw Error();if((await stat(p)).isDirectory())p=resolve(p,'index.html');res.writeHead(200,{'Content-Type':mime[extname(p)]??'application/octet-stream'}).end(await readFile(p));}catch{res.writeHead(404).end()}});if(server)await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,...(process.env.CI?{}:{channel:'chrome'})}),records=[];
try{for(const s of sites.filter(s=>!process.argv.includes('--skip-depth')||s.group!=='depth')){
 const base=server?`http://127.0.0.1:${server.address().port}/${s.repository}/`:s.url,page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[],failed=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push({url:r.url(),status:r.status()})});page.on('request',r=>requests.push(r.url()));
 try{await page.goto(base);if(s.group==='depth'){await page.waitForFunction(()=>!document.querySelector('[data-screen="result"]').hidden,{timeout:360000});assert.match(await page.locator('#backend-label').textContent(),/WASM|WebGPU|wasm|webgpu/i);assert.ok(await page.locator('#depth-canvas').evaluate(c=>{const d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;return new Set(d.filter((_,i)=>i%4===0)).size>10}));}
 else{await page.waitForFunction(()=>document.body.dataset.state==='ready');if(s.group==='models'){await page.waitForFunction(()=>document.querySelector('#real-host').dataset.example==='done',{timeout:120000});const data=JSON.parse(await page.locator('[data-result]').textContent());if(s.scene==='02'){assert.ok(data.detections.some(d=>d.class==='person'&&d.score>.5));}else{assert.equal(data.trainingCount,2);assert.equal(data.example.testPhotoInTraining,false);assert.ok(data.losses.at(-1)<data.losses[0]);assert.equal(data.embeddingDimension,1024);}}
 else await page.waitForFunction(()=>document.querySelector('#real-host .real-status')?.textContent.match(/完成|已计算/));
 assert.equal(await page.locator('#scene-nav').count(),0);assert.equal(await page.locator('iframe').count(),0);assert.ok(await page.locator('#real-host canvas').count()>0);assert.equal(requests.filter(u=>u.startsWith(new URL(base).origin)&&!u.startsWith(base)).length,0,'site requests sibling resources');}
 if(s.chapter==='007'){await page.route('**/indoor.jpg',async route=>{await new Promise(r=>setTimeout(r,700));await route.continue()});await page.locator('button[data-example]').click();await page.waitForFunction(()=>document.querySelector('.real-status').textContent.includes('解码'));await page.locator('[data-cancel]').click();await page.waitForTimeout(1000);assert.match(await page.locator('.real-status').textContent(),/已取消/);assert.equal(await page.locator('[data-json]').isDisabled(),true);await page.unroute('**/indoor.jpg');await page.locator('button[data-example]').click();await page.waitForFunction(()=>document.querySelector('#real-host').dataset.example==='done',{timeout:120000});}
 if(s.group==='depth'){const race=await browser.newPage();await race.goto(base+'?e2e=1&manual');await race.route('**/assets/samples/indoor.jpg',async route=>{await new Promise(r=>setTimeout(r,900));try{await route.continue()}catch{}});await race.locator('[data-sample]').first().click();await race.locator('#album-input').setInputFiles(resolve(root,s.repository,'assets/samples/street.jpg'));await race.waitForFunction(()=>!document.querySelector('[data-screen="result"]').hidden);const dimensions=await race.locator('#source-canvas').evaluate(c=>[c.width,c.height]);await race.waitForTimeout(1200);assert.deepEqual(await race.locator('#source-canvas').evaluate(c=>[c.width,c.height]),dimensions);assert.ok(dimensions[0]>dimensions[1],'new landscape upload should win over indoor sample');await race.close();}
 await page.screenshot({path:resolve(qa,`${s.repository}-desktop.png`),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:resolve(qa,`${s.repository}-mobile.png`),fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);records.push({repository:s.repository,url:base,realExample:true,independent:true,mobile:true,requests:requests.length});console.log(`PASS ${s.repository}`);
 }catch(e){console.log('Failed',s.repository,await page.locator('body').innerText());throw e;}finally{await page.close()}
 }await writeFile(resolve(qa,process.env.INDEPENDENT_ONLINE?'online-report.json':'report.json'),JSON.stringify({records},null,2));
}finally{await browser.close();if(server)await new Promise(r=>server.close(r))}
