import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {serve} from '../scripts/serve.mjs';
const dir=resolve(import.meta.dirname,'../../.superpowers/sdd/real-image-labs/qa');await mkdir(dir,{recursive:true});
const server=process.env.COURSE_BASE?null:await serve(),base=process.env.COURSE_BASE??`http://127.0.0.1:${server.address().port}/course-labs/`;
const browser=await chromium.launch({headless:true,...(process.env.CI?{}:{channel:'chrome'})});
const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true}),errors=[],external=[],records=[];
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(new URL(base).origin)&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))external.push(r.url());});
const host=page.locator('#real-host');
async function route(chapter,scene){await page.goto(`${base}chapter-${chapter}/?scene=${scene}`);await host.locator('canvas,img').first().waitFor();await page.waitForFunction(()=>document.querySelector('#real-host .real-status')?.textContent.match(/完成|已计算|已载入/));}
async function photoMode(value){await host.locator('[data-photo]').selectOption(value);await page.waitForFunction(()=>document.querySelector('#real-host .real-status').textContent.includes('输入已更换'));}
async function act(selector){await host.locator(selector).click();await page.waitForFunction(()=>document.querySelector('#real-host .real-status').textContent.startsWith('完成'),{timeout:120000});}
async function data(){return JSON.parse(await host.locator('[data-result]').textContent());}
async function view(label){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,label);await page.screenshot({path:resolve(dir,`${label}-desktop.png`),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,label+' mobile');await page.screenshot({path:resolve(dir,`${label}-mobile.png`),fullPage:true});await page.setViewportSize({width:1440,height:1000});}
try{
 await route('005','02');const before=await host.locator('[data-view="2"]').evaluate(c=>c.toDataURL());await host.locator('[data-param="max"]').fill('16');await host.locator('[data-param="max"]').dispatchEvent('input');await page.waitForTimeout(200);assert.notEqual(await host.locator('[data-view="2"]').evaluate(c=>c.toDataURL()),before);await host.locator('[data-view="0"]').click({position:{x:150,y:100}});assert.match(await host.locator('[data-inspect]').textContent(),/SAD/);await view('stereo');records.push({case:'real stereo',parameters:true,pixels:true});
 for(const [chapter,scene] of [['005','03'],['006','01'],['006','02'],['006','04']]){await route(chapter,scene);assert.ok((await host.locator('.real-metrics').textContent()).length>10);if(scene==='04'){const loss=await host.locator('[data-log]').textContent();assert.match(loss,/MSE=/);await host.locator('[data-k]').fill('2');await host.locator('[data-run]').click();await page.waitForFunction(()=>document.querySelector('#real-host .real-status').textContent.startsWith('完成'));assert.notEqual(await host.locator('[data-log]').textContent(),loss);}const downloaded=page.waitForEvent('download');await host.locator('[data-json]').click();const file=await downloaded;await file.saveAs(resolve(dir,`${chapter}-${scene}.json`));const json=JSON.parse(await readFile(resolve(dir,`${chapter}-${scene}.json`),'utf8'));assert.equal(json.chapter,chapter);await view(`${chapter}-${scene}`);records.push({chapter,scene,realPixels:true,export:true});}
 await route('007','03');await act('[data-run]');let result=await data();assert.ok(result.embeddingDimension>=256);assert.equal(result.imagenetTop5.length,5);await host.locator('[data-label]').selectOption('0');await act('[data-add]');await photoMode('street');await host.locator('[data-label]').selectOption('1');await act('[data-add]');await act('[data-train]');result=await data();assert.equal(result.trainingCount,2);assert.ok(result.losses.at(-1)<result.losses[0]);await view('real-trained-head');records.push({case:'MobileNet and frozen head',dimensions:result.embeddingDimension,initialLoss:result.losses[0],finalLoss:result.losses.at(-1)});
 const downloaded=page.waitForEvent('download');await host.locator('[data-json]').click();await (await downloaded).saveAs(resolve(dir,'trained-head.json'));
 await page.evaluate(()=>{const h=document.querySelector('#real-host'),s=h.querySelector('[data-photo]');s.value='person';s.dispatchEvent(new Event('change'));h.querySelector('[data-run]').click();});assert.match(await host.locator('.real-status').textContent(),/未就绪|更换/);await page.waitForFunction(()=>document.querySelector('#real-host .real-status').textContent.includes('输入已更换'));assert.equal(await host.locator('[data-json]').isDisabled(),true);records.push({case:'photo decode gates immediate inference',passed:true});
 await host.locator('[data-upload]').setInputFiles({name:'broken.png',mimeType:'image/png',buffer:Buffer.from('broken')});await page.waitForFunction(()=>document.querySelector('#real-host .real-status').textContent.includes('加载失败'));await host.locator('[data-run]').click();assert.match(await host.locator('.real-status').textContent(),/未就绪|加载失败/);assert.equal(await host.locator('[data-json]').isDisabled(),true);records.push({case:'failed model image blocks stale inference',passed:true});
 await route('008','02');await act('[data-run]');result=await data();assert.ok(result.detections.some(x=>x.class==='person'&&x.score>.5));await view('coco-detection');records.push({case:'COCO-SSD real inference',detections:result.detections});await host.locator('[data-label]').selectOption('0.6');await act('[data-run]');assert.ok((await data()).detections.length<=result.detections.length);
 // Fast chapter switches must not let an older mount overwrite the new UI.
 await page.goto(`${base}chapter-006/?scene=01`);await page.locator('#scene-nav a').filter({hasText:'04 '}).click();await page.waitForFunction(()=>document.querySelector('#real-host [data-k]')&&document.querySelector('#real-host .real-status').textContent.startsWith('完成'));assert.equal(await host.locator('[data-k]').count(),1);
 await page.goto(`${base}chapter-004/?scene=03`);await host.locator('img').waitFor();assert.equal(await host.locator('[data-depth-open]').count(),1);assert.equal(await host.locator('iframe').count(),0);records.push({case:'Depth Anything explicit remote launch',preview:true});
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 await writeFile(resolve(dir,'report.json'),JSON.stringify({base,records,errors,external},null,2));console.log(`PASS ${records.length} real-image browser cases, actual model inference, mobile and exports`);
}finally{await browser.close();await new Promise(r=>server?server.close(r):r());}
