import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {serve} from '../scripts/serve.mjs';
const dir=resolve(import.meta.dirname,'../../.superpowers/sdd/temporal-course/qa');await mkdir(dir,{recursive:true});
const server=process.env.COURSE_BASE?null:await serve(),base=process.env.COURSE_BASE??`http://127.0.0.1:${server.address().port}/course-labs/`;
const browser=await chromium.launch({headless:true,...(process.env.CI?{}:{channel:'chrome'})}),page=await browser.newPage({acceptDownloads:true}),errors=[],cases=[];page.on('pageerror',e=>errors.push(e.message));
const $=s=>page.locator(`#real-host ${s}`),complete=()=>page.waitForFunction(()=>document.querySelector('#real-host .real-status')?.textContent.startsWith('完成'));
const data=async()=>{const p=page.waitForEvent('download');await $('[data-json]').click();const d=await p;const path=resolve(dir,`result-${Date.now()}.json`);await d.saveAs(path);return JSON.parse(await readFile(path,'utf8'))};
try{
 await page.goto(`${base}chapter-005/?scene=03`);await complete();let r=await data();assert.equal(r.records.length,29);assert.equal(r.source.kind,'sample');assert.ok(r.records.some(x=>x.tracks.some(t=>t.history.length>5)));assert.ok(r.records.every(x=>x.dt>.19&&x.dt<.21));cases.push('real 30-frame sequence and persistent trajectories');
 await $('[data-time]').fill('0');await $('[data-time]').dispatchEvent('input');assert.match(await $('[data-time-label]').textContent(),/1\/29/);await $('[data-next]').click();assert.match(await $('[data-time-label]').textContent(),/2\/29/);await $('[data-play]').click();await page.waitForTimeout(500);assert.ok(Number(await $('[data-time]').inputValue())>1);await $('[data-play]').click();cases.push('scrub, single step and timed playback');
 await $('[data-levels]').selectOption('2');await $('[data-fb]').fill('.5');await $('[data-run]').click();await complete();r=await data();assert.equal(r.parameters.fb,.5);assert.equal(r.parameters.levels,2);cases.push('parameter replay and truthful export');
 const asset=resolve(import.meta.dirname,'../real/assets/temporal');await $('[data-upload]').setInputFiles([{name:'frame-10.jpg',mimeType:'image/jpeg',buffer:await readFile(resolve(asset,'frame-001.jpg'))},{name:'frame-2.jpg',mimeType:'image/jpeg',buffer:await readFile(resolve(asset,'frame-000.jpg'))}]);await complete();r=await data();assert.deepEqual(r.source.names,['frame-2.jpg','frame-10.jpg']);assert.equal(r.records.length,1);cases.push('numeric frame order');
 await $('[data-upload]').setInputFiles({name:'broken.png',mimeType:'image/png',buffer:Buffer.from('broken')});await page.waitForFunction(()=>document.querySelector('#real-host .real-status').textContent.includes('加载失败'));assert.equal(await $('[data-json]').isDisabled(),true);cases.push('invalid input blocks stale export');
 await $('[data-limit]').selectOption('30');await $('[data-video]').setInputFiles(resolve(asset,'pedestrians.mp4'));await complete();r=await data();assert.equal(r.source.kind,'video');assert.ok(r.records.length>=27);assert.ok(r.records.every(x=>x.dt>.19&&x.dt<.21));cases.push('actual H264 video decode');
 await page.goto(`${base}chapter-006/?scene=01`);await complete();r=await data();assert.ok(r.records.some(x=>x.metrics.foreground>0));await $('[data-freeze]').uncheck();await $('[data-alpha]').fill('.5');await $('[data-run]').click();await complete();r=await data();assert.equal(r.parameters.freeze,false);assert.equal(r.parameters.alpha,.5);cases.push('background update comparison');
 // Test the camera API using a real-photo canvas MediaStream, without claiming physical hardware coverage.
 await page.evaluate(async url=>{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=384;canvas.height=288;canvas.getContext('2d').drawImage(image,0,0,384,288);window.testCamera={canvas,tracks:[],facing:[]};Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:async o=>{window.testCamera.facing.push(o.video.facingMode.ideal);const s=canvas.captureStream(10);window.testCamera.tracks.push(...s.getTracks());const timer=setInterval(()=>{if(s.getTracks().every(t=>t.readyState==='ended'))clearInterval(timer);else canvas.getContext('2d').drawImage(image,0,0,384,288)},100);return s}}})},`${base}real/assets/temporal/frame-000.jpg`);
 await $('.camera-panel summary').click();await $('[data-camera]').click();await page.waitForFunction(()=>document.querySelector('[data-snap]').disabled===false);await $('[data-snap]').click();await page.waitForTimeout(100);await $('[data-snap]').click();await $('[data-run]').click();await complete();r=await data();assert.equal(r.source.kind,'camera');assert.equal(r.records.length,1);assert.ok(await page.evaluate(()=>testCamera.tracks.every(t=>t.readyState==='ended')));cases.push('camera snapshots and release after replay');
 await $('[data-camera]').click();await page.waitForFunction(()=>document.querySelector('[data-snap]').disabled===false);await $('[data-live]').click();await page.waitForFunction(()=>document.querySelector('[data-time]').max>2);await $('[data-live]').click();assert.ok(await $('[data-json]').isEnabled());await $('[data-snap]').click();assert.equal(await $('[data-json]').isDisabled(),true);assert.equal(await $('[data-png]').isDisabled(),true);cases.push('snapshot invalidates previous live export');await $('[data-facing]').selectOption('user');await page.waitForFunction(()=>document.querySelector('[data-snap]').disabled===false);assert.ok(await page.evaluate(()=>testCamera.facing.includes('user')));await page.locator('#scene-nav a').filter({hasText:'04 '}).click();await complete();assert.ok(await page.evaluate(()=>testCamera.tracks.every(t=>t.readyState==='ended')));cases.push('real-time camera, lens switch and navigation cleanup');
 await page.goto(`${base}chapter-005/?scene=03`);await complete();await page.evaluate(()=>Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:async()=>{throw new DOMException('denied','NotAllowedError')}}}));await $('.camera-panel summary').click();await $('[data-camera]').click();await page.waitForFunction(()=>document.querySelector('.real-status').textContent.includes('未获得相机权限'));assert.equal(await $('[data-live]').isDisabled(),true);cases.push('camera permission denial');
 await $('[data-default]').click();await $('[data-cancel]').click();await page.waitForTimeout(500);assert.match(await $('.real-status').textContent(),/已取消/);await $('[data-default]').click();await complete();cases.push('cancel blocks obsolete load');
 await page.route('**/temporal-core.mjs',async route=>{await new Promise(r=>setTimeout(r,1000));await route.continue().catch(()=>{})});
 await page.goto(`${base}chapter-006/?scene=01`);await page.waitForFunction(()=>document.querySelector('.real-status')?.textContent==='计算连续帧…');
 await page.evaluate(()=>{const c=document.createElement('canvas');c.width=384;c.height=288;window.raceTracks=[];window.cameraCanvas=c;Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:async()=>{const s=c.captureStream(10);raceTracks.push(...s.getTracks());const timer=setInterval(()=>{if(s.getTracks().every(t=>t.readyState==='ended'))clearInterval(timer);else c.getContext('2d').fillRect(0,0,10,10)},100);return s}}})});
 await $('[data-cancel]').click();await $('.camera-panel summary').click();await $('[data-camera]').click();await page.waitForFunction(()=>!document.querySelector('[data-snap]').disabled);await page.locator('#scene-nav a').filter({hasText:'04 '}).click();await complete();await page.waitForTimeout(1200);assert.ok(await page.evaluate(()=>raceTracks.every(t=>t.readyState==='ended')));cases.push('cancel initial worker init still releases camera on navigation');await page.unroute('**/temporal-core.mjs');
 await page.locator('#scene-nav a').filter({hasText:'01 '}).click();await complete();await $('.camera-panel summary').click();await $('[data-camera]').click();await page.waitForFunction(()=>!document.querySelector('[data-snap]').disabled);await $('[data-live]').click();await page.waitForFunction(()=>Number(document.querySelector('[data-time]').max)>2);await page.evaluate(()=>{cameraCanvas.width=288;cameraCanvas.height=384});await page.waitForFunction(()=>document.querySelector('.real-status').textContent.includes('计算失败'));const fail=await $('.real-status').textContent();await page.waitForTimeout(700);assert.equal(await $('.real-status').textContent(),fail);await $('[data-stop-camera]').click();cases.push('camera dimensions change stops processing with stable error');
 await page.goto(`${base}chapter-005/?scene=03`);await complete();
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:resolve(dir,'camera-mobile.png'),fullPage:true});cases.push('mobile layout');
 assert.deepEqual(errors,[]);await writeFile(resolve(dir,'report.json'),JSON.stringify({base,cases,errors,cameraCoverage:'browser MediaStream fixture; physical mobile camera requires device verification'},null,2));console.log(`PASS ${cases.length} temporal/video/camera cases`);
}catch(e){console.log('FAILED cases',cases);console.log(await page.evaluate(()=>({status:document.querySelector('.real-status')?.textContent,secure:isSecureContext,video:{width:document.querySelector('[data-preview]')?.videoWidth,ready:document.querySelector('[data-preview]')?.readyState},tracks:window.testCamera?.tracks.map(t=>({ready:t.readyState,enabled:t.enabled}))})));throw e;}finally{await browser.close();await new Promise(r=>server?server.close(r):r())}
